// Code generated by appmanager dev_generate host protocol extraction. DO NOT EDIT.
// Host wire types and typed callers for the callIDs declared in
// .appdef `permissions:`. Regenerate with appmanager.dev_generate.
//
// Covered host calls:
//   registry.query -> registry.query  req RegistryQueryReq  resp RegistryQueryResp
//   state.get -> state.get  req StateKeyReq  resp StateGetResp
//   state.set -> state.set  req StateSetReq  resp opaque
//
// Listened host events (listen <kind> {}): payload types below; OnXxx
// handlers live in handlers.go and are dispatched by the pluginhost.
//   app_event  payload AppEventMessage
//   app_lifecycle  payload AppLifecycleEvent

package main

import (
	"encoding/json"
	"fmt"
	sdk "github.com/qomos-w/sporemind-plugin-sdk"
)

// Host schema IDs for the extracted types.
const (
	HostSchemaIDAppEventMessage   uint64 = 2060
	HostSchemaIDAppLifecycleEvent uint64 = 2005
	HostSchemaIDCallableParam     uint64 = 848
)

type AppEventMessage struct {
	ID      string `json:"Id"`
	Event   string `json:"Event"`
	Payload []byte `json:"Payload"`
	Sender  string `json:"Sender,omitempty"`
}

type AppLifecycleEvent struct {
	Kind       string `json:"Kind"`
	ID         string `json:"Id"`
	Runtime    string `json:"Runtime"`
	State      string `json:"State"`
	Version    string `json:"Version,omitempty"`
	Generation int64  `json:"Generation,omitempty"`
	Error      string `json:"Error,omitempty"`
}

type CallableParam struct {
	Name        string `json:"Name"`
	Type        string `json:"Type"`
	Description string `json:"Description,omitempty"`
	Required    bool   `json:"Required,omitempty"`
}

type RegistryCallableMeta struct {
	CallID       string          `json:"CallID"`
	Service      string          `json:"Service,omitempty"`
	Kind         string          `json:"Kind,omitempty"`
	Params       []CallableParam `json:"Params,omitempty"`
	FinalType    string          `json:"FinalType,omitempty"`
	FinalFields  []CallableParam `json:"FinalFields,omitempty"`
	Permission   string          `json:"Permission,omitempty"`
	EffectKind   string          `json:"EffectKind,omitempty"`
	Description  string          `json:"Description,omitempty"`
	ReqSchemaId  int32           `json:"ReqSchemaId,omitempty"`
	RespSchemaId int32           `json:"RespSchemaId,omitempty"`
}

type RegistryQueryReq struct {
	Service  string `json:"service,omitempty"`
	Callable string `json:"callable,omitempty"`
	Limit    int    `json:"limit,omitempty"`
	Cursor   string `json:"cursor,omitempty"`
}

type RegistryQueryResp struct {
	Items      []RegistryCallableMeta `json:"Items"`
	NextCursor string                 `json:"NextCursor,omitempty"`
}

type StateGetResp struct {
	Value []byte `json:"Value"`
	Found bool   `json:"Found,omitempty"`
}

type StateKeyReq struct {
	Key string `json:"key"`
}

type StateSetReq struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

// CallRegistryQuery invokes the host callable registry.query (backing registry.query, capability registry.read).
// discovers callable metadata across the running actor tree; served locally by the pluginhost (filters on Service/Callable, offset cursor pagination; metadata only, no credential values)
func CallRegistryQuery(host sdk.Host, req RegistryQueryReq) (RegistryQueryResp, error) {
	raw, err := host.Invoke("registry.query", req)
	if err != nil {
		return RegistryQueryResp{}, err
	}
	var resp RegistryQueryResp
	if err := json.Unmarshal(raw, &resp); err != nil {
		return RegistryQueryResp{}, fmt.Errorf("registry.query: decode response: %w", err)
	}
	return resp, nil
}

// CallStateGet invokes the host callable state.get (backing state.get, capability app.state).
// per-app key-value storage routed by the pluginhost; the host injects the calling plugin's identity
func CallStateGet(host sdk.Host, req StateKeyReq) (StateGetResp, error) {
	raw, err := host.Invoke("state.get", req)
	if err != nil {
		return StateGetResp{}, err
	}
	var resp StateGetResp
	if err := json.Unmarshal(raw, &resp); err != nil {
		return StateGetResp{}, fmt.Errorf("state.get: decode response: %w", err)
	}
	return resp, nil
}

// CallStateSet invokes the host callable state.set (backing state.set, capability app.state).
// per-app key-value storage routed by the pluginhost; Value is base64-encoded []byte on the wire
func CallStateSet(host sdk.Host, req StateSetReq) ([]byte, error) {
	return host.Invoke("state.set", req)
}
