package testutil

// SDK example staging helpers for the native plugin e2e tests.
//
// The checked-in example go.mod (sporemind-plugin-sdk/examples/hello, kept
// in-repo) uses relative replaces that resolve within the repository; inside
// an agent worktree of sporemind the spore module is not reachable that way,
// so building the example in place fails. StageExampleModuleDir copies the
// example sources into a temp module whose go.mod replaces the SDK with the
// checkout found by walking up and spore with the module dir resolved via
// `go list -m` (the repo's go.mod replace points at the real checkout in
// both layouts). go.sum is gitignored in this repo and absent in fresh
// worktrees, so the staged module is tidied before building.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// StageExampleModuleDir copies every file of srcDir into <outDir>/module,
// rewrites the go.mod replaces to absolute paths, and runs `go mod tidy` in
// the staged module so its go.sum exists regardless of checkout layout.
// Subdirectories are not copied — the SDK example plugin sources are flat.
// Returns the staged module directory.
func StageExampleModuleDir(t testing.TB, srcDir, outDir string) string {
	t.Helper()
	sdkDir := locateSDKDir(t, srcDir)
	sporeDir, err := resolveModuleDir(t, "github.com/qomos-w/spore")
	if err != nil {
		t.Skipf("cannot resolve spore module for the plugin build: %v", err)
	}

	modDir := filepath.Join(outDir, "module")
	if err := os.MkdirAll(modDir, 0o755); err != nil {
		t.Fatalf("mkdir staged module: %v", err)
	}
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		t.Fatalf("read example dir %s: %v", srcDir, err)
	}
	for _, e := range entries {
		if e.IsDir() || e.Name() == "go.sum" { // regenerated by tidy below
			continue
		}
		data, err := os.ReadFile(filepath.Join(srcDir, e.Name()))
		if err != nil {
			t.Fatalf("read example file %s: %v", e.Name(), err)
		}
		if err := os.WriteFile(filepath.Join(modDir, e.Name()), data, 0o644); err != nil {
			t.Fatalf("write staged file %s: %v", e.Name(), err)
		}
	}

	goMod, err := os.ReadFile(filepath.Join(srcDir, "go.mod"))
	if err != nil {
		t.Fatalf("read example go.mod: %v", err)
	}
	if err := os.WriteFile(filepath.Join(modDir, "go.mod"), rewriteExampleReplaces(t, goMod, sdkDir, sporeDir), 0o644); err != nil {
		t.Fatalf("write staged go.mod: %v", err)
	}

	GoRun(t, modDir, nil, "mod", "tidy")
	return modDir
}

// locateSDKDir walks up from srcDir until a directory containing a
// "sporemind-plugin-sdk" child is found.
func locateSDKDir(t testing.TB, srcDir string) string {
	t.Helper()
	dir, ok := findSDKDirFrom(srcDir)
	if !ok {
		t.Fatalf("sporemind-plugin-sdk directory not found above %s", srcDir)
	}
	return dir
}

// FindSDKDir walks up from the current working directory until a parent
// directory contains a "sporemind-plugin-sdk" child — normally the in-repo
// checkout at the sporemind repository root. It returns ok=false when no
// checkout is found so callers can t.Skip instead of fail.
func FindSDKDir(t testing.TB) (dir string, ok bool) {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	return findSDKDirFrom(wd)
}

func findSDKDirFrom(from string) (string, bool) {
	dir := from
	for {
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		if info, err := os.Stat(filepath.Join(parent, "sporemind-plugin-sdk")); err == nil && info.IsDir() {
			return filepath.Join(parent, "sporemind-plugin-sdk"), true
		}
		dir = parent
	}
}

// resolveModuleDir returns the on-disk directory of a module as resolved by
// `go list -m` from the test's own module context (no GOWORK override: the
// repo's go.work / go.mod replace resolves spore in both the worktree and
// the plain checkout layout).
func resolveModuleDir(t testing.TB, mod string) (string, error) {
	t.Helper()
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", mod)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("go list -m %s: %v: %s", mod, err, out)
	}
	return strings.TrimSpace(string(out)), nil
}

// rewriteExampleReplaces pins the example module's replace targets to the
// absolute SDK + spore directories. Pre-existing relative targets (which
// only resolve in the main checkout layout) are replaced and missing entries
// are appended. Both go.mod styles are handled: inline "replace <mod> => …"
// lines and "<mod> => …" entries inside "replace (…)" blocks; require-block
// entries are never touched.
func rewriteExampleReplaces(t testing.TB, goMod []byte, sdkDir, sporeDir string) []byte {
	t.Helper()
	repl := map[string]string{
		"github.com/qomos-w/spore":                 filepath.ToSlash(sporeDir),
		"github.com/qomos-w/sporemind-plugin-sdk": filepath.ToSlash(sdkDir),
	}
	lines := strings.Split(string(goMod), "\n")
	out := make([]string, 0, len(lines)+len(repl))
	seen := map[string]bool{}
	inRequire := false // entries inside "require (" look identical to replace entries
	for _, ln := range lines {
		trimmed := strings.TrimSpace(ln)
		switch {
		case trimmed == "":
			out = append(out, ln)
			continue
		case trimmed == "require (":
			inRequire = true
			out = append(out, ln)
			continue
		case trimmed == ")":
			inRequire = false
			out = append(out, ln)
			continue
		}
		if inRequire {
			out = append(out, ln)
			continue
		}
		inline := strings.HasPrefix(trimmed, "replace ")
		rest := strings.TrimSpace(strings.TrimPrefix(trimmed, "replace "))
		replaced := false
		for mod, abs := range repl {
			if rest == mod || strings.HasPrefix(rest, mod+" ") || strings.HasPrefix(rest, mod+"=>") {
				if inline {
					out = append(out, "replace "+mod+" => "+abs)
				} else {
					out = append(out, mod+" => "+abs)
				}
				seen[mod] = true
				replaced = true
				break
			}
		}
		if !replaced {
			out = append(out, ln)
		}
	}
	for mod, abs := range repl {
		if !seen[mod] {
			out = append(out, "replace "+mod+" => "+abs)
		}
	}
	return []byte(strings.Join(out, "\n"))
}

// GoRun runs the go tool in dir with GOWORK=off (so the staged module's own
// replaces apply; the repo-level go.work would otherwise override them) and
// -mod=mod (so module files may be updated during tidy/build), plus the
// given env overrides. Any failure fails t.
func GoRun(t testing.TB, dir string, envExtra []string, args ...string) {
	t.Helper()
	out, err := GoRunOutput(dir, envExtra, args...)
	if err != nil {
		t.Fatalf("go %s: %v\n%s", strings.Join(args, " "), err, out)
	}
}

// GoRunOutput runs the go tool like GoRun but returns the combined output
// and error instead of failing t (used by overridable build hooks).
func GoRunOutput(dir string, envExtra []string, args ...string) ([]byte, error) {
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	cmd.Env = envWith(append(envExtra, "GOWORK=off", "GOFLAGS=-mod=mod"))
	return cmd.CombinedOutput()
}

// envWith appends key=value overrides, replacing any pre-existing entries.
func envWith(overrides []string) []string {
	env := make([]string, 0, len(os.Environ())+len(overrides))
	for _, kv := range os.Environ() {
		key := kv
		if i := strings.IndexByte(kv, '='); i >= 0 {
			key = kv[:i]
		}
		replace := false
		for _, ov := range overrides {
			if strings.HasPrefix(ov, key+"=") {
				replace = true
				break
			}
		}
		if !replace {
			env = append(env, kv)
		}
	}
	return append(env, overrides...)
}