// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FeatureFlags holds the set of feature flags gated by build type and flavor.
 */
export class FeatureFlags {
    "flags": { [_ in string]?: boolean };

    /** Creates a new FeatureFlags instance. */
    constructor($$source: Partial<FeatureFlags> = {}) {
        if (!("flags" in $$source)) {
            this["flags"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureFlags instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureFlags {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField0_0($$parsedSource["flags"]);
        }
        return new FeatureFlags($$parsedSource as Partial<FeatureFlags>);
    }
}

/**
 * Info is the assembled build metadata snapshot.
 */
export class Info {
    "version": string;
    "build_type": string;
    "build_flavor": string;
    "commit": string;
    "build_time": string;
    "dirty": boolean;
    "public_version": string;
    "channel": string;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("build_type" in $$source)) {
            this["build_type"] = "";
        }
        if (!("build_flavor" in $$source)) {
            this["build_flavor"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("build_time" in $$source)) {
            this["build_time"] = "";
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("public_version" in $$source)) {
            this["public_version"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
