// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConsoleEntry mirrors the frontend console-patch store entry.
 */
export class ConsoleEntry {
    "level": string;
    "message": string;
    "time": number;
    "location"?: string;

    /** Creates a new ConsoleEntry instance. */
    constructor($$source: Partial<ConsoleEntry> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsoleEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsoleEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsoleEntry($$parsedSource as Partial<ConsoleEntry>);
    }
}
