package codegen

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/qomos-w/sporemind/pkg/appdef"
	gen "github.com/qomos-w/sporemind/pkg/domain/gen"
)

// FileBundleCallsGo is the generated typed-caller artifact for bundle-level
// permissions: for every `plugin.<depID>.<bundleSlug>` permission whose
// dependency is registered, the dependency's bundle tools are re-exported as
// typed Go request/response structs plus CallBundle* caller functions. Written
// by dev_generate; hand edits are overwritten.
const FileBundleCallsGo = "bundle_calls.gen.go"

// bundleCallsMarker identifies files produced by this emitter so regeneration
// can safely overwrite (or stub out) previous output.
const bundleCallsMarker = "Code generated by appmanager dev_generate bundle call extraction"

// BundleDep carries one registered dependency's manifest, schema descriptors
// and package hash, resolved by the dev_generate handler from the appmanager
// registry. Only registered deps produce typed callers; callable-level
// permissions keep hostproto.gen.go's raw-JSON form.
type BundleDep struct {
	Manifest    gen.AppManifest
	Descriptors map[string]gen.AppObjectDescriptor
	PackageHash string
}

// BundleSnapshot records what a generation resolved from each dependency for
// bundle-level permissions: the expanded callable set and the schema hashes
// the typed structs were rendered from. The dev_gate drift gate recomputes
// this against the CURRENT registry and fails when they differ — the
// generated typed callers and the runtime authorization must agree.
type BundleSnapshot struct {
	DepID          string            `json:"DepID"`
	DepVersion     string            `json:"DepVersion"`
	DepPackageHash string            `json:"DepPackageHash"`
	Permissions    []string          `json:"Permissions"` // resolved bundle-level permissions
	Callables      []string          `json:"Callables"`   // expanded plugin.<dep>.<callable> callIDs
	SchemaHashes   map[string]string `json:"SchemaHashes"`
}

// bundleTypeEmitter renders one dependency's descriptor structs under a
// dep-prefixed namespace so they cannot collide with the app's own
// schemas_gen.go types or another dependency's identically named types.
type bundleTypeEmitter struct {
	dep      BundleDep
	prefix   string            // e.g. "AppTranslator"
	emitted  map[string]string // prefixed go type name -> declaration
	rendered map[string]bool   // descriptor names already rendered/queued
	called   map[string]bool   // caller function names already emitted
	hashes   map[string]bool   // descriptor names referenced
	// needsRaw/needsJSON/needsFmt accumulate the file's import requirements.
	needsRaw  bool // a field used json.RawMessage
	needsJSON bool // a caller decodes a typed response
	needsFmt  bool // a caller wraps a decode error
}

// bundlePermissionTarget resolves one `plugin.<depID>.<name>` permission
// against the registered deps: longest depID prefix wins (dep IDs may contain
// dots).
func bundlePermissionTarget(perm string, deps map[string]BundleDep) (depID, name string, ok bool) {
	if !strings.HasPrefix(perm, "plugin.") {
		return "", "", false
	}
	rest := strings.TrimPrefix(perm, "plugin.")
	best := ""
	for id := range deps {
		if strings.HasPrefix(rest, id+".") && len(id) > len(best) {
			best = id
		}
	}
	if best == "" {
		return "", "", false
	}
	name = strings.TrimPrefix(rest, best+".")
	if name == "" {
		return "", "", false
	}
	return best, name, true
}

// depBundleSlugs reproduces the canonical bundle-slug map (slugify + dedup),
// mirroring appmanager's claimBundleSlug so codegen resolves bundle identity
// with the exact rule registration uses.
func depBundleSlugs(dep BundleDep) map[string][]gen.AppBundleTool {
	used := map[string]bool{}
	out := map[string][]gen.AppBundleTool{}
	for _, b := range dep.Manifest.Bundles {
		slug := bundleSlugify(b.Title)
		if slug == "" {
			slug = "bundle"
		}
		base := slug
		for i := 2; used[slug]; i++ {
			slug = fmt.Sprintf("%s-%d", base, i)
		}
		used[slug] = true
		out[slug] = b.Tools
	}
	return out
}

// bundleSlugify mirrors appmanager.slugify: lowercase, every rune outside
// [a-z0-9] becomes '-', trimmed of '-'.
func bundleSlugify(title string) string {
	title = strings.ToLower(title)
	var b strings.Builder
	for _, r := range title {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

// camelStem converts a dot/dash separated id like "app.translator" or
// "translate_run" into a Go identifier stem "AppTranslator" / "TranslateRun".
func camelStem(id string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(id, func(r rune) bool { return !(unicode.IsLetter(r) || unicode.IsDigit(r)) }) {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

// emitBundleCalls renders FileBundleCallsGo for the app's declared
// permissions and produces the per-dependency snapshots (callable set +
// schema hashes) persisted into the GeneratedManifest for the drift gate.
// Permissions that do not resolve to a registered dependency's bundle stay in
// hostproto.gen.go's raw-JSON form and produce no typed output here.
func emitBundleCalls(pkgName string, app *appdef.AppDef, deps map[string]BundleDep) (string, []BundleSnapshot, error) {
	if pkgName == "" {
		pkgName = "main"
	}
	declaredDeps := map[string]bool{}
	for _, d := range app.Dependencies {
		declaredDeps[d.ID] = true
	}

	snapshots := map[string]*BundleSnapshot{}
	emitterByDep := map[string]*bundleTypeEmitter{}
	var emitters []*bundleTypeEmitter
	var callers []string
	needsJSON, needsFmt, needsSDK := false, false, false

	for _, perm := range app.AppMeta.Permissions {
		depID, name, ok := bundlePermissionTarget(perm, deps)
		if !ok {
			continue
		}
		dep := deps[depID]
		tools, isBundle := depBundleSlugs(dep)[name]
		if !isBundle {
			continue // callable-level permission: raw caller in hostproto.gen.go
		}
		if !declaredDeps[depID] {
			// Registration rejects this (undeclared dependency); keep
			// generating so dev_gate can report the precise error.
			continue
		}
		snap, hasSnap := snapshots[depID]
		if !hasSnap {
			snap = &BundleSnapshot{
				DepID: depID, DepVersion: dep.Manifest.Version, DepPackageHash: dep.PackageHash,
				SchemaHashes: map[string]string{},
			}
			snapshots[depID] = snap
		}
		snap.Permissions = append(snap.Permissions, perm)
		em, hasEmitter := emitterByDep[depID]
		if !hasEmitter {
			em = &bundleTypeEmitter{
				dep:      dep,
				prefix:   camelStem(depID),
				emitted:  map[string]string{},
				rendered: map[string]bool{},
				called:   map[string]bool{},
				hashes:   map[string]bool{},
			}
			emitterByDep[depID] = em
			emitters = append(emitters, em)
		}
		for _, tool := range tools {
			callID := "plugin." + depID + "." + tool.CallableID
			snap.Callables = append(snap.Callables, callID)
			caller, err := em.renderCaller(callID, tool.CallableID)
			if err != nil {
				return "", nil, fmt.Errorf("bundle permission %q: %w", perm, err)
			}
			if caller != "" {
				callers = append(callers, caller)
				needsSDK = true
			}
		}
	}

	for _, em := range emitters {
		if em.needsRaw || em.needsJSON {
			needsJSON = true
		}
		if em.needsFmt {
			needsFmt = true
		}
		snap := snapshots[em.dep.Manifest.ID]
		for name := range em.hashes {
			snap.SchemaHashes[name] = schemaHashFor(em.dep, name)
		}
		sort.Strings(snap.Callables)
		snap.Callables = dedupSorted(snap.Callables)
	}
	snapList := make([]BundleSnapshot, 0, len(snapshots))
	for _, id := range sortedKeys(snapshots) {
		s := snapshots[id]
		sort.Strings(s.Permissions)
		s.Permissions = dedupSorted(s.Permissions)
		snapList = append(snapList, *s)
	}

	var b strings.Builder
	b.WriteString("// " + bundleCallsMarker + "\n")
	b.WriteString("//\n")
	b.WriteString("// Typed callers for bundle-level plugin permissions. Each `plugin.<dep>.<bundle>`\n")
	b.WriteString("// permission declared in .appdef was resolved against the dependency's\n")
	b.WriteString("// REGISTERED manifest at generation time; its bundle tools are re-exported\n")
	b.WriteString("// here as dep-prefixed request/response structs and CallBundle* functions.\n")
	b.WriteString("// The expansion snapshot lives in the GeneratedManifest (dev_gate drift gate).\n")
	if len(callers) == 0 {
		b.WriteString("//\n")
		b.WriteString("// No bundle-level permissions resolved; this file is intentionally empty.\n")
	}
	b.WriteString("\npackage " + pkgName + "\n\n")

	var imports []string
	if needsJSON {
		imports = append(imports, `"encoding/json"`)
	}
	if needsFmt {
		imports = append(imports, `"fmt"`)
	}
	if needsSDK {
		imports = append(imports, `sdk "github.com/qomos-w/sporemind-plugin-sdk"`)
	}
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString("\t" + imp + "\n")
		}
		b.WriteString(")\n\n")
	}

	for _, em := range emitters {
		names := make([]string, 0, len(em.emitted))
		for name := range em.emitted {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			b.WriteString(em.emitted[name])
		}
	}
	for _, caller := range callers {
		b.WriteString(caller)
	}

	src := b.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return "", nil, fmt.Errorf("bundle_calls.gen.go: %w\n--- source ---\n%s", err, src)
	}
	return string(formatted), snapList, nil
}

func findCallable(callables []gen.AppCallableDescriptor, id string) (gen.AppCallableDescriptor, bool) {
	for _, c := range callables {
		if c.ID == id {
			return c, true
		}
	}
	return gen.AppCallableDescriptor{}, false
}

func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// dedupSorted collapses adjacent duplicates of an already-sorted slice.
func dedupSorted(items []string) []string {
	out := items[:0]
	for i, item := range items {
		if i == 0 || item != items[i-1] {
			out = append(out, item)
		}
	}
	return out
}

func schemaHashFor(dep BundleDep, name string) string {
	for _, ref := range dep.Manifest.Schemas {
		if ref.Name == name && ref.Hash != "" {
			return ref.Hash
		}
	}
	if desc, ok := dep.Descriptors[name]; ok {
		raw, err := json.Marshal(desc)
		if err == nil {
			sum := sha256.Sum256(raw)
			return hex.EncodeToString(sum[:])
		}
	}
	return ""
}

// ComputeBundleSnapshots re-resolves an appdef's bundle-level permissions
// against the given dependency view WITHOUT writing any file. The dev_gate
// drift gate uses it to compare what the CURRENT registry would authorize
// against what dev_generate snapshotted; an error means the appdef or a
// dependency manifest is inconsistent (unknown tool callable, missing
// descriptor), which the gate surfaces as its root cause.
func ComputeBundleSnapshots(appdefContent string, deps map[string]BundleDep) ([]BundleSnapshot, error) {
	app, diags, err := appdef.ParseFile(appdefContent)
	if err != nil {
		return nil, fmt.Errorf("parse appdef: %w", err)
	}
	if len(diags) > 0 {
		return nil, fmt.Errorf("appdef diagnostics: %v", diags)
	}
	_, snapshots, err := emitBundleCalls("", app, deps)
	return snapshots, err
}

// typeName is the dep-prefixed Go name for one of the dependency's schemas.
func (e *bundleTypeEmitter) typeName(descName string) string {
	return e.prefix + descName
}

// queueType renders one descriptor struct (recursively queueing referenced
// structs) and records the schema as used.
func (e *bundleTypeEmitter) queueType(name string) error {
	if e.rendered[name] {
		return nil
	}
	desc, ok := e.dep.Descriptors[name]
	if !ok {
		return fmt.Errorf("schema %q not found in the dependency's descriptors", name)
	}
	e.rendered[name] = true
	e.hashes[name] = true
	var b strings.Builder
	fmt.Fprintf(&b, "// %s mirrors the dependency schema %q.\n", e.typeName(name), name)
	fmt.Fprintf(&b, "type %s struct {\n", e.typeName(name))
	for _, f := range desc.Fields {
		gt, err := e.renderType(f.Type)
		if err != nil {
			return fmt.Errorf("field %s: %w", f.Name, err)
		}
		tag := fmt.Sprintf("json:\"%s\"", f.Name)
		if f.Optional {
			tag = fmt.Sprintf("json:\"%s,omitempty\"", f.Name)
		}
		fmt.Fprintf(&b, "\t%s %s `%s`\n", exportName(f.Name), gt, tag)
	}
	b.WriteString("}\n\n")
	e.emitted[e.typeName(name)] = b.String()
	return nil
}

func (e *bundleTypeEmitter) renderType(t gen.AppTypeDescriptor) (string, error) {
	switch t.Kind {
	case "scalar":
		switch t.Name {
		case "string":
			return "string", nil
		case "bool":
			return "bool", nil
		case "int":
			return "int32", nil
		case "uint":
			return "uint32", nil
		case "long":
			return "int64", nil
		case "ulong":
			return "uint64", nil
		case "short":
			return "int16", nil
		case "ushort":
			return "uint16", nil
		case "byte":
			return "uint8", nil
		case "float":
			return "float32", nil
		case "double":
			return "float64", nil
		case "bytes":
			return "[]byte", nil
		case "any", "object":
			e.needsRaw = true
			return "json.RawMessage", nil
		default:
			return "", fmt.Errorf("unknown scalar %q", t.Name)
		}
	case "array":
		if t.Element == nil {
			return "", fmt.Errorf("array without element")
		}
		el, err := e.renderType(*t.Element)
		return "[]" + el, err
	case "map":
		if t.Key == nil || t.Value == nil {
			return "", fmt.Errorf("map without key/value")
		}
		k, err := e.renderType(*t.Key)
		if err != nil {
			return "", err
		}
		v, err := e.renderType(*t.Value)
		if err != nil {
			return "", err
		}
		return "map[" + k + "]" + v, nil
	case "struct":
		if t.ClassName == "" {
			return "", fmt.Errorf("struct reference without class name")
		}
		if err := e.queueType(t.ClassName); err != nil {
			return "", err
		}
		return e.typeName(t.ClassName), nil
	case "enum":
		return "string", nil
	default:
		return "", fmt.Errorf("unsupported type kind %q", t.Kind)
	}
}

// renderCaller emits the typed CallBundle* function for one bundle tool.
// Returns "" when the callable is unknown to the dep manifest (an error the
// caller wraps) or the function was already emitted (duplicate tool across
// two granted bundles of the same dependency).
func (e *bundleTypeEmitter) renderCaller(callID, callableID string) (string, error) {
	callable, found := findCallable(e.dep.Manifest.Callables, callableID)
	if !found {
		return "", fmt.Errorf("bundle tool %q has no callable in the dependency's manifest", callableID)
	}
	funcName := "CallBundle" + e.prefix + camelStem(callableID)
	if e.called[funcName] {
		return "", nil
	}
	e.called[funcName] = true
	reqType := ""
	if callable.RequestSchema != "" && callable.RequestSchema != "void" {
		if err := e.queueType(callable.RequestSchema); err != nil {
			return "", err
		}
		reqType = e.typeName(callable.RequestSchema)
	}
	respType := ""
	if callable.ResponseSchema != "" && callable.ResponseSchema != "void" {
		if err := e.queueType(callable.ResponseSchema); err != nil {
			return "", err
		}
		respType = e.typeName(callable.ResponseSchema)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// %s invokes the bundle callable %s (typed re-export of the\n", funcName, callID)
	b.WriteString("// dependency's registered schema; the raw-JSON caller lives in hostproto.gen.go).\n")
	switch {
	case reqType != "" && respType != "":
		e.needsJSON, e.needsFmt = true, true
		fmt.Fprintf(&b, "func %s(host sdk.Host, req %s) (%s, error) {\n", funcName, reqType, respType)
		fmt.Fprintf(&b, "\traw, err := host.Invoke(%q, req)\n", callID)
		fmt.Fprintf(&b, "\tif err != nil {\n\t\treturn %s{}, err\n\t}\n", respType)
		fmt.Fprintf(&b, "\tvar resp %s\n", respType)
		b.WriteString("\tif err := json.Unmarshal(raw, &resp); err != nil {\n")
		fmt.Fprintf(&b, "\t\treturn %s{}, fmt.Errorf(%q, err)\n", respType, callID+": decode response: %w")
		b.WriteString("\t}\n\treturn resp, nil\n}\n\n")
	case reqType != "":
		fmt.Fprintf(&b, "func %s(host sdk.Host, req %s) ([]byte, error) {\n", funcName, reqType)
		fmt.Fprintf(&b, "\treturn host.Invoke(%q, req)\n}\n\n", callID)
	default:
		fmt.Fprintf(&b, "func %s(host sdk.Host) ([]byte, error) {\n", funcName)
		fmt.Fprintf(&b, "\treturn host.Invoke(%q, nil)\n}\n\n", callID)
	}
	return b.String(), nil
}

// exportName guarantees a Go-exported field identifier; the json tag keeps
// the original wire name.
func exportName(name string) string {
	if name == "" {
		return name
	}
	r := []rune(name)
	return string(unicode.ToUpper(r[0])) + string(r[1:])
}
