package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/qomos-w/spore/schema"
	"github.com/qomos-w/sporemind/pkg/appbinding"
	gen "github.com/qomos-w/sporemind/pkg/domain/gen"
)

// FileHostProtoGo is the generated host-protocol artifact: the wire types and
// typed Call/Stream caller functions for the host callIDs an app declared in
// .appdef `permissions:`. Written by dev_generate; hand edits are overwritten.
const FileHostProtoGo = "hostproto.gen.go"

// hostProtoMarker identifies files produced by this emitter so regeneration
// can safely overwrite (or stub out) previous extraction output.
const hostProtoMarker = "Code generated by appmanager dev_generate host protocol extraction"

// hostProtoPkgs are the only packages whose named struct types may appear in
// an emitted contract. Anything else is a foreign type the extractor does not
// understand and must not silently truncate.
var hostProtoPkgs = map[string]bool{
	"github.com/qomos-w/sporemind/pkg/domain/gen": true,
	"github.com/qomos-w/sporemind/pkg/domain":     true,
	"github.com/qomos-w/sporemind/pkg/appbinding": true,
}

// HostCallSchema is the resolved wire protocol behind one SDK-facing host
// callID as extracted from the embedded gospore manifest. It describes the
// BACKING callable; for callIDs whose SDK contract differs (llm.*, state.*,
// config.get, provider.get) the appbinding SDKCallCatalog overrides it.
type HostCallSchema struct {
	TargetCallID  string // actual callID of the backing callable (alias target)
	Service       string // service name of the backing callable
	Streaming     bool   // backing callable streams chunks
	ReqSchemaID   uint64 // request payload schema ID (0 = opaque)
	FinalSchemaID uint64 // final/response payload schema ID (0 = opaque)
	ChunkSchemaID uint64 // stream chunk schema ID (0 = not streaming)
}

// HostCallSpec is one declared host call resolved for emission. Catalog
// entries carry explicit reflect types; pass-through calls resolve their
// schema IDs to types via the host registry before emission.
type HostCallSpec struct {
	CallID       string
	TargetCallID string // backing callable (display only)
	Service      string
	// Streaming marks chunked delivery over Host.InvokeStream. Derived, never
	// declared: catalog entries derive it from stream-route presence
	// (IsSDKCallStreaming), pass-through callables from the manifest
	// (backing actor's actor.Streaming[T]() declaration). Entries with
	// StreamChunkKind emit the typed sdk.LLMChunk decode; other streaming
	// entries emit the generic envelope-bytes onChunk.
	Streaming       bool
	ReqType         reflect.Type // nil = no request payload
	RespType        reflect.Type // nil = opaque response (raw bytes)
	StreamChunkKind string       // "LLMChunk" decodes via sdk.ForwardLLMChunks; "" = raw envelope bytes
	Note            string       // local-call note surfaced in doc comments
	// BundleCall marks a cross-plugin invocation (plugin.<target>.<callable>).
	// The request and response are opaque JSON forwarded to the target plugin's
	// process via the host bridge bundleDispatch — no typed structs are
	// available because the target plugin's types are not in the host ProtoPkgs
	// allowlist. The emitted caller takes and returns json.RawMessage.
	BundleCall bool
}

// SpecFromSchema resolves a pass-through HostCallSchema into a HostCallSpec
// by looking its schema IDs up in the host registry.
func SpecFromSchema(callID string, hs HostCallSchema) (HostCallSpec, error) {
	spec := HostCallSpec{
		CallID:       callID,
		TargetCallID: hs.TargetCallID,
		Service:      hs.Service,
		Streaming:    hs.Streaming,
	}
	if spec.TargetCallID == "" {
		spec.TargetCallID = callID
	}
	if hs.ReqSchemaID != 0 {
		typ, ok := schema.StructTypeByID(hs.ReqSchemaID)
		if !ok {
			return spec, fmt.Errorf("request schema ID %d (callID %q) not found in the host registry", hs.ReqSchemaID, callID)
		}
		spec.ReqType = typ
	}
	if hs.FinalSchemaID != 0 {
		typ, ok := schema.StructTypeByID(hs.FinalSchemaID)
		if !ok {
			return spec, fmt.Errorf("response schema ID %d (callID %q) not found in the host registry", hs.FinalSchemaID, callID)
		}
		spec.RespType = typ
	}
	return spec, nil
}

// SpecFromSDKCall adapts an appbinding SDKCallCatalog entry.
// SpecFromSDKCall adapts an appbinding SDKCallCatalog entry. Streaming is
// derived from route presence (the actor.Streaming[T]() chain), never stored
// on the catalog entry.
func SpecFromSDKCall(sc appbinding.SDKCall) HostCallSpec {
	spec := HostCallSpec{
		CallID:          sc.CallID,
		TargetCallID:    appbinding.ResolveHostCall(sc.CallID),
		Streaming:       appbinding.IsSDKCallStreaming(sc.CallID),
		ReqType:         sc.ReqType,
		RespType:        sc.RespType,
		StreamChunkKind: sc.StreamChunkKind,
		Note:            sc.Note,
	}
	if spec.TargetCallID == "" {
		spec.TargetCallID = sc.CallID
	}
	return spec
}

// hostProtoEmitter accumulates type declarations for the dependency closure
// of the requested host schemas.
type hostProtoEmitter struct {
	// ids maps schema ID -> canonical type name (inverted gen.SchemaIDs).
	ids map[string]uint64
	// emitted collects rendered type declarations keyed by type name.
	emitted map[string]string
	// pkgs records type name -> source package path, so two packages
	// exporting the same type name collide loudly instead of overwriting.
	pkgs map[string]string
	// needsTime tracks whether the time import is required.
	needsTime bool
	// needsJSONRaw tracks whether the encoding/json import is required for
	// json.RawMessage fields (raw passthrough JSON that must NOT collapse to
	// []byte — []byte unmarshals from a base64 string on the wire, while the
	// host sends raw JSON).
	needsJSONRaw bool
}

// fileHasMarker reports whether the file at dir/name exists and contains the
// given generated-marker comment line.
func fileHasMarker(dir, name, marker string) bool {
	data, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		return false
	}
	return bytes.Contains(data, []byte(marker))
}

// goPackageName returns the Go package clause of the app directory's existing
// .go files, defaulting to "main". The emitted host protocol file must share
// the app's package to compile alongside handlers.go and schemas_gen.go.
func goPackageName(dir string) string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "main"
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "package ") {
				name := strings.TrimSpace(strings.TrimPrefix(line, "package "))
				if name != "" {
					return name
				}
			}
		}
	}
	return "main"
}

// EmitHostProtocolGo renders FileHostProtoGo for the given declared host
// calls: the wire types (dependency closure) plus one typed Call function per
// callID and one Stream function per streaming callID. listens adds the host
// event payload types for `listen <kind> {}` declarations (the matching OnXxx
// handler stubs land in handlers.go). Output is deterministic: callIDs, event
// kinds, type names and constants are sorted. Foreign named types (anything
// outside the host protocol packages, builtins, any, or time.Time) are hard
// errors — they indicate a schema pattern the extractor does not understand
// and must not silently truncate. json.RawMessage is the one named []byte
// exception: it is rendered verbatim instead of collapsing to []byte, whose
// base64-string wire form would fail to decode the host's raw JSON.
func EmitHostProtocolGo(pkgName string, calls map[string]HostCallSpec, listens []appbinding.HostEvent) (string, error) {
	if pkgName == "" {
		pkgName = "main"
	}
	e := &hostProtoEmitter{
		ids:     make(map[string]uint64),
		emitted: make(map[string]string),
		pkgs:    make(map[string]string),
	}
	for id, name := range gen.SchemaIDs {
		e.ids[name] = id
	}

	var callIDs []string
	for callID := range calls {
		callIDs = append(callIDs, callID)
	}
	sort.Strings(callIDs)

	// Resolve and walk every payload type; errors surface unknown schema IDs
	// (gmanifest/registry drift) and unsupported types.
	walked := map[string]bool{}
	for _, callID := range callIDs {
		c := calls[callID]
		for _, typ := range []reflect.Type{c.ReqType, c.RespType} {
			if typ == nil {
				continue
			}
			if err := e.walk(typ, walked); err != nil {
				return "", fmt.Errorf("host protocol: %s (callID %q): %w", typ.Name(), callID, err)
			}
		}
	}
	for _, le := range listens {
		if le.PayloadType == nil {
			continue
		}
		if err := e.walk(le.PayloadType, walked); err != nil {
			return "", fmt.Errorf("host protocol: %s (listen %q): %w", le.PayloadType.Name(), le.Kind, err)
		}
	}

	var b strings.Builder
	b.WriteString("// " + hostProtoMarker + ". DO NOT EDIT.\n")
	b.WriteString("// Host wire types and typed callers for the callIDs declared in\n")
	b.WriteString("// .appdef `permissions:`. Regenerate with appmanager.dev_generate.\n")
	if len(callIDs) > 0 {
		b.WriteString("//\n")
		b.WriteString("// Covered host calls:\n")
		for _, callID := range callIDs {
			c := calls[callID]
			line := fmt.Sprintf("//   %s -> %s", callID, c.TargetCallID)
			if c.ReqType != nil {
				line += "  req " + c.ReqType.Name()
			}
			if c.RespType != nil {
				line += "  resp " + c.RespType.Name()
			} else {
				line += "  resp opaque"
			}
			if c.Streaming {
				line += "  (streaming)"
			}
			b.WriteString(line + "\n")
		}
	}
	if len(listens) > 0 {
		b.WriteString("//\n")
		b.WriteString("// Listened host events (listen <kind> {}): payload types below; OnXxx\n")
		b.WriteString("// handlers live in handlers.go and are dispatched by the pluginhost.\n")
		for _, le := range listens {
			payload := "opaque"
			if le.PayloadType != nil {
				payload = le.PayloadType.Name()
			}
			fmt.Fprintf(&b, "//   %s  payload %s\n", le.Kind, payload)
		}
	}
	if len(callIDs) == 0 && len(listens) == 0 {
		b.WriteString("//\n")
		b.WriteString("// No host capabilities declared; this file is intentionally empty.\n")
	}
	b.WriteString("\npackage " + pkgName + "\n\n")

	// Render typed callers first so import requirements are known before the
	// import block is written.
	var funcs strings.Builder
	needsJSON := false
	needsFmt := false
	needsSDK := false
	needsCtx := false
	for _, callID := range callIDs {
		c := calls[callID]
		src, uses := renderHostCallers(c)
		if uses {
			needsSDK = true
			// Bundle callers marshal json.RawMessage directly (no extracted
			// RespType), so they require the json import too.
			if c.BundleCall {
				needsJSON = true
			}
			if c.RespType != nil {
				needsJSON = true
				needsFmt = true
			}
			if c.Streaming {
				needsCtx = true
			}
		}
		funcs.WriteString(src)
	}

	var imports []string
	if needsCtx {
		imports = append(imports, `"context"`)
	}
	if needsJSON || e.needsJSONRaw {
		imports = append(imports, `"encoding/json"`)
	}
	if needsFmt {
		imports = append(imports, `"fmt"`)
	}
	if needsSDK {
		imports = append(imports, `sdk "github.com/qomos-w/sporemind-plugin-sdk"`)
	}
	if e.needsTime {
		imports = append(imports, `"time"`)
	}
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString("\t" + imp + "\n")
		}
		b.WriteString(")\n\n")
	}

	names := make([]string, 0, len(e.emitted))
	for name := range e.emitted {
		names = append(names, name)
	}
	sort.Strings(names)

	if len(names) > 0 {
		b.WriteString("// Host schema IDs for the extracted types.\n")
		b.WriteString("const (\n")
		for _, name := range names {
			if id, ok := e.ids[name]; ok {
				fmt.Fprintf(&b, "\tHostSchemaID%s uint64 = %d\n", name, id)
			}
		}
		b.WriteString(")\n\n")
	}

	for _, name := range names {
		b.WriteString(e.emitted[name])
		b.WriteString("\n")
	}

	b.WriteString(funcs.String())

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("host protocol: format emitted source: %w", err)
	}
	return string(src), nil
}

// hostCallAcronyms uppercases callID segments that read as acronyms so
// llm.complete renders as CallLLMComplete, not CallLlmComplete.
var hostCallAcronyms = map[string]string{
	"llm": "LLM",
}

// callIDToFuncName mangles a host callID into an exported Go identifier stem:
// segments split on . _ - are title-cased (llm → LLM via the acronym table).
func callIDToFuncName(callID string) string {
	parts := strings.FieldsFunc(callID, func(r rune) bool {
		return r == '.' || r == '_' || r == '-'
	})
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if up, ok := hostCallAcronyms[p]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// renderHostCallers emits the typed caller functions for one declared host
// call: CallXxx (unary Invoke) for every callID and StreamXxx (chunked
// delivery) for streaming catalog entries that delegate to an SDK typed
// streaming client. It reports whether any function was rendered.
func renderHostCallers(c HostCallSpec) (string, bool) {
	if c.BundleCall {
		var b strings.Builder
		stem := callIDToFuncName(c.CallID)
		fmt.Fprintf(&b, "// Call%s invokes the bundle callable %s (cross-plugin call routed by the\n", stem, c.CallID)
		b.WriteString("// host bridge to the target plugin's process). Request and response are\n")
		b.WriteString("// opaque JSON; the target plugin owns their schema.\n")
		fmt.Fprintf(&b, "func Call%s(host sdk.Host, req json.RawMessage) ([]byte, error) {\n", stem)
		fmt.Fprintf(&b, "\treturn host.Invoke(%q, req)\n", c.CallID)
		b.WriteString("}\n\n")
		return b.String(), true
	}
	if c.ReqType != nil && c.ReqType.Kind() != reflect.Struct {
		return "", false // non-struct requests have no typed caller shape
	}
	var b strings.Builder
	stem := callIDToFuncName(c.CallID)

	doc := fmt.Sprintf("// Call%s invokes the host callable %s (backing %s, capability %s).",
		stem, c.CallID, c.TargetCallID, appbinding.HostCallCapability(c.CallID))
	if c.Note != "" {
		doc += "\n// " + c.Note
	}
	b.WriteString(doc + "\n")
	if c.ReqType != nil && c.RespType != nil {
		fmt.Fprintf(&b, "func Call%s(host sdk.Host, req %s) (%s, error) {\n", stem, c.ReqType.Name(), c.RespType.Name())
		fmt.Fprintf(&b, "\traw, err := host.Invoke(%q, req)\n", c.CallID)
		b.WriteString("\tif err != nil {\n")
		fmt.Fprintf(&b, "\t\treturn %s{}, err\n", c.RespType.Name())
		b.WriteString("\t}\n")
		fmt.Fprintf(&b, "\tvar resp %s\n", c.RespType.Name())
		b.WriteString("\tif err := json.Unmarshal(raw, &resp); err != nil {\n")
		fmt.Fprintf(&b, "\t\treturn %s{}, fmt.Errorf(%q, err)\n", c.RespType.Name(), c.CallID+": decode response: %w")
		b.WriteString("\t}\n")
		b.WriteString("\treturn resp, nil\n")
		b.WriteString("}\n\n")
	} else if c.ReqType != nil {
		fmt.Fprintf(&b, "func Call%s(host sdk.Host, req %s) ([]byte, error) {\n", stem, c.ReqType.Name())
		fmt.Fprintf(&b, "\treturn host.Invoke(%q, req)\n", c.CallID)
		b.WriteString("}\n\n")
	} else if c.RespType != nil {
		fmt.Fprintf(&b, "func Call%s(host sdk.Host) (%s, error) {\n", stem, c.RespType.Name())
		fmt.Fprintf(&b, "\traw, err := host.Invoke(%q, nil)\n", c.CallID)
		b.WriteString("\tif err != nil {\n")
		fmt.Fprintf(&b, "\t\treturn %s{}, err\n", c.RespType.Name())
		b.WriteString("\t}\n")
		fmt.Fprintf(&b, "\tvar resp %s\n", c.RespType.Name())
		b.WriteString("\tif err := json.Unmarshal(raw, &resp); err != nil {\n")
		fmt.Fprintf(&b, "\t\treturn %s{}, fmt.Errorf(%q, err)\n", c.RespType.Name(), c.CallID+": decode response: %w")
		b.WriteString("\t}\n")
		b.WriteString("\treturn resp, nil\n")
		b.WriteString("}\n\n")
	} else {
		fmt.Fprintf(&b, "func Call%s(host sdk.Host) ([]byte, error) {\n", stem)
		fmt.Fprintf(&b, "\treturn host.Invoke(%q, nil)\n", c.CallID)
		b.WriteString("}\n\n")
	}

	if c.Streaming && c.StreamChunkKind == "LLMChunk" {
		fmt.Fprintf(&b, "// Stream%s streams the host callable %s: chunks flow to onChunk in\n", stem, c.CallID)
		b.WriteString("// arrival order decoded as sdk.LLMChunk (via sdk.ForwardLLMChunks), the\n")
		b.WriteString("// return value is the same aggregated terminal as the unary form.\n")
		b.WriteString("// Transports without streaming degrade to zero chunks plus the terminal.\n")
		if c.ReqType != nil {
			fmt.Fprintf(&b, "func Stream%s(host sdk.Host, req %s, onChunk func(sdk.LLMChunk) error) (%s, error) {\n", stem, c.ReqType.Name(), c.RespType.Name())
			fmt.Fprintf(&b, "\treturn Stream%sCtx(context.Background(), host, req, onChunk)\n", stem)
			b.WriteString("}\n\n")
			fmt.Fprintf(&b, "// Stream%sCtx is Stream%s with a cancellation root: ctx expiry aborts the\n", stem, stem)
			b.WriteString("// stream and (on transports implementing sdk.CanceledHost) asks the host to\n")
			b.WriteString("// abort its upstream dispatch. Other transports keep waiting until the\n")
			b.WriteString("// terminal arrives.\n")
			fmt.Fprintf(&b, "func Stream%sCtx(ctx context.Context, host sdk.Host, req %s, onChunk func(sdk.LLMChunk) error) (%s, error) {\n", stem, c.ReqType.Name(), c.RespType.Name())
			b.WriteString("\tvar raw []byte\n")
			b.WriteString("\tvar err error\n")
			b.WriteString("\tif ch, ok := host.(sdk.CanceledHost); ok {\n")
			fmt.Fprintf(&b, "\t\traw, err = ch.InvokeStreamCtx(ctx, %q, req, sdk.ForwardLLMChunks(onChunk))\n", c.CallID)
			b.WriteString("\t} else {\n")
			fmt.Fprintf(&b, "\t\traw, err = host.InvokeStream(%q, req, sdk.ForwardLLMChunks(onChunk))\n", c.CallID)
			b.WriteString("\t}\n")
		} else {
			fmt.Fprintf(&b, "func Stream%s(host sdk.Host, onChunk func(sdk.LLMChunk) error) (%s, error) {\n", stem, c.RespType.Name())
			fmt.Fprintf(&b, "\treturn Stream%sCtx(context.Background(), host, onChunk)\n", stem)
			b.WriteString("}\n\n")
			fmt.Fprintf(&b, "// Stream%sCtx is Stream%s with a cancellation root: ctx expiry aborts the\n", stem, stem)
			b.WriteString("// stream and (on transports implementing sdk.CanceledHost) asks the host to\n")
			b.WriteString("// abort its upstream dispatch. Other transports keep waiting until the\n")
			b.WriteString("// terminal arrives.\n")
			fmt.Fprintf(&b, "func Stream%sCtx(ctx context.Context, host sdk.Host, onChunk func(sdk.LLMChunk) error) (%s, error) {\n", stem, c.RespType.Name())
			b.WriteString("\tvar raw []byte\n")
			b.WriteString("\tvar err error\n")
			b.WriteString("\tif ch, ok := host.(sdk.CanceledHost); ok {\n")
			fmt.Fprintf(&b, "\t\traw, err = ch.InvokeStreamCtx(ctx, %q, nil, sdk.ForwardLLMChunks(onChunk))\n", c.CallID)
			b.WriteString("\t} else {\n")
			fmt.Fprintf(&b, "\t\traw, err = host.InvokeStream(%q, nil, sdk.ForwardLLMChunks(onChunk))\n", c.CallID)
			b.WriteString("\t}\n")
		}
		b.WriteString("\tif err != nil {\n")
		fmt.Fprintf(&b, "\t\treturn %s{}, err\n", c.RespType.Name())
		b.WriteString("\t}\n")
		fmt.Fprintf(&b, "\tvar resp %s\n", c.RespType.Name())
		b.WriteString("\tif err := json.Unmarshal(raw, &resp); err != nil {\n")
		fmt.Fprintf(&b, "\t\treturn %s{}, fmt.Errorf(%q, err)\n", c.RespType.Name(), c.CallID+": decode terminal: %w")
		b.WriteString("\t}\n")
		b.WriteString("\treturn resp, nil\n")
		b.WriteString("}\n\n")
	} else if c.Streaming {
		// Generic pass-through streaming (no SDK convenience facade): onChunk
		// receives each chunk's raw wire bytes — the generic host envelope
		// {"kind": "...", "data": {...}} — and the app decodes its own domain
		// chunk vocabulary. The terminal is the call's RespType (same shape as
		// the unary form) or opaque bytes.
		fmt.Fprintf(&b, "// Stream%s streams the host callable %s: onChunk receives each\n", stem, c.CallID)
		b.WriteString("// chunk's raw wire bytes (the generic {\"kind\", \"data\"} envelope — decode\n")
		b.WriteString("// your domain chunk from data); the return value is the same terminal as\n")
		b.WriteString("// the unary form. Transports without streaming degrade to zero chunks\n")
		b.WriteString("// plus the terminal.\n")
		respName := "[]byte"
		if c.RespType != nil {
			respName = c.RespType.Name()
		}
		if c.ReqType != nil {
			fmt.Fprintf(&b, "func Stream%s(host sdk.Host, req %s, onChunk func([]byte) error) (%s, error) {\n", stem, c.ReqType.Name(), respName)
			fmt.Fprintf(&b, "\treturn host.InvokeStream(%q, req, onChunk)\n", c.CallID)
		} else {
			fmt.Fprintf(&b, "func Stream%s(host sdk.Host, onChunk func([]byte) error) (%s, error) {\n", stem, respName)
			fmt.Fprintf(&b, "\treturn host.InvokeStream(%q, nil, onChunk)\n", c.CallID)
		}
		b.WriteString("}\n\n")
	}
	return b.String(), true
}

// walk renders typ (and its transitive closure) into the emitter. walked
// guards against cycles in the host type graph.
func (e *hostProtoEmitter) walk(typ reflect.Type, walked map[string]bool) error {
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	switch typ.Kind() {
	case reflect.Slice, reflect.Array:
		return e.walk(typ.Elem(), walked)
	case reflect.Map:
		if err := e.walk(typ.Key(), walked); err != nil {
			return err
		}
		return e.walk(typ.Elem(), walked)
	case reflect.Interface:
		if typ.NumMethod() != 0 {
			return fmt.Errorf("non-empty interface %s is not extractable", typ.String())
		}
		return nil
	case reflect.Struct:
		if typ.PkgPath() == "time" && typ.Name() == "Time" {
			e.needsTime = true
			return nil
		}
		name := typ.Name()
		if name != "" {
			if !hostProtoPkgs[typ.PkgPath()] {
				return fmt.Errorf("foreign named type %s is outside the host protocol packages", typ.String())
			}
			if prev, ok := e.pkgs[name]; ok {
				if prev != typ.PkgPath() {
					return fmt.Errorf("type name collision: %s exported by both %s and %s", name, prev, typ.PkgPath())
				}
			} else {
				e.pkgs[name] = typ.PkgPath()
			}
			if walked[name] {
				return nil
			}
			walked[name] = true
			var b strings.Builder
			fmt.Fprintf(&b, "type %s struct {\n", name)
			for i := 0; i < typ.NumField(); i++ {
				f := typ.Field(i)
				if f.PkgPath != "" { // unexported
					continue
				}
				fieldType, err := e.renderType(f.Type)
				if err != nil {
					return fmt.Errorf("field %s: %w", f.Name, err)
				}
				if len(f.Tag) > 0 {
					fmt.Fprintf(&b, "\t%s %s `%s`\n", f.Name, fieldType, f.Tag)
				} else {
					fmt.Fprintf(&b, "\t%s %s\n", f.Name, fieldType)
				}
			}
			b.WriteString("}\n")
			e.emitted[name] = b.String()
		}
		// Anonymous structs and closure of named fields.
		for i := 0; i < typ.NumField(); i++ {
			f := typ.Field(i)
			if f.PkgPath != "" {
				continue
			}
			if err := e.walk(f.Type, walked); err != nil {
				return fmt.Errorf("field %s: %w", f.Name, err)
			}
		}
		return nil
	default:
		// Builtins (string, ints, floats, bool) render via typ.String().
		if typ.Name() == "" {
			return fmt.Errorf("unnamed non-struct type %s is not extractable", typ.String())
		}
		return nil
	}
}

// renderType renders a Go type expression for typ, failing on constructs the
// extractor does not support.
func (e *hostProtoEmitter) renderType(typ reflect.Type) (string, error) {
	switch typ.Kind() {
	case reflect.Pointer:
		elem, err := e.renderType(typ.Elem())
		if err != nil {
			return "", err
		}
		return "*" + elem, nil
	case reflect.Slice:
		if typ.Elem().Kind() == reflect.Uint8 {
			// Raw passthrough JSON fields (json.RawMessage; Go 1.25 reports the
			// alias's canonical name jsontext.Value) must survive extraction:
			// rendering them as []byte would unmarshal from a base64 string,
			// while the host emits raw JSON (e.g. LLMResp.Usage).
			if (typ.PkgPath() == "encoding/json" && typ.Name() == "RawMessage") ||
				(typ.PkgPath() == "encoding/json/jsontext" && typ.Name() == "Value") {
				e.needsJSONRaw = true
				return "json.RawMessage", nil
			}
			return "[]byte", nil
		}
		elem, err := e.renderType(typ.Elem())
		if err != nil {
			return "", err
		}
		return "[]" + elem, nil
	case reflect.Array:
		elem, err := e.renderType(typ.Elem())
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("[%d]%s", typ.Len(), elem), nil
	case reflect.Map:
		key, err := e.renderType(typ.Key())
		if err != nil {
			return "", err
		}
		val, err := e.renderType(typ.Elem())
		if err != nil {
			return "", err
		}
		return "map[" + key + "]" + val, nil
	case reflect.Interface:
		if typ.NumMethod() != 0 {
			return "", fmt.Errorf("non-empty interface %s is not extractable", typ.String())
		}
		return "any", nil
	case reflect.Struct:
		if typ.PkgPath() == "time" && typ.Name() == "Time" {
			e.needsTime = true
			return "time.Time", nil
		}
		if typ.Name() == "" {
			// Anonymous struct: render inline.
			var b strings.Builder
			b.WriteString("struct {\n")
			for i := 0; i < typ.NumField(); i++ {
				f := typ.Field(i)
				if f.PkgPath != "" {
					continue
				}
				fieldType, err := e.renderType(f.Type)
				if err != nil {
					return "", fmt.Errorf("field %s: %w", f.Name, err)
				}
				if len(f.Tag) > 0 {
					fmt.Fprintf(&b, "\t%s %s `%s`\n", f.Name, fieldType, f.Tag)
				} else {
					fmt.Fprintf(&b, "\t%s %s\n", f.Name, fieldType)
				}
			}
			b.WriteString("}")
			return b.String(), nil
		}
		if !hostProtoPkgs[typ.PkgPath()] {
			return "", fmt.Errorf("foreign named type %s is outside the host protocol packages", typ.String())
		}
		return typ.Name(), nil
	default:
		if typ.Name() == "" {
			return "", fmt.Errorf("unnamed type %s is not extractable", typ.String())
		}
		return typ.String(), nil
	}
}
