// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gen$0 from "./gen/models.js";

/**
 * AgentSessionForkResp is the response for agent.session.fork.
 */
export const AgentSessionForkResp = gen$0.AgentSessionForkResp;

/**
 * AgentSessionForkResp is the response for agent.session.fork.
 */
export type AgentSessionForkResp = gen$0.AgentSessionForkResp;

/**
 * DesktopWindowState is the persisted desktop window geometry.
 */
export const DesktopWindowState = gen$0.DesktopWindowState;

/**
 * DesktopWindowState is the persisted desktop window geometry.
 */
export type DesktopWindowState = gen$0.DesktopWindowState;
