package sdk

import (
	"fmt"
	"regexp"

	gen "github.com/qomos-w/sporemind-plugin-sdk/gen"
)

// toolNameRe is the validation pattern for LLM-side tool names.
// Mirrors gospore actor.ValidateToolName: names must be non-empty and match
// [a-zA-Z0-9_-]+ so they are safe for LLM provider tool-name constraints.
var toolNameRe = regexp.MustCompile(`^[a-zA-Z0-9_-]+$`)

// ErrNotImplemented is returned by handler stubs generated by the codegen
// tool. Callers can grep for this sentinel to verify all declared callables
// have been implemented before submitting.
var ErrNotImplemented = fmt.Errorf("not implemented")

// ValidateToolName checks whether name is a valid LLM tool name.
// Returns nil if valid, an error describing the violation otherwise.
// Replicates gospore actor.ValidateToolName semantics so the SDK does not
// need to import the host runtime.
func ValidateToolName(name string) error {
	if name == "" {
		return fmt.Errorf("tool name cannot be empty")
	}
	if !toolNameRe.MatchString(name) {
		return fmt.Errorf("tool name %q contains invalid characters; only [a-zA-Z0-9_-] are allowed", name)
	}
	return nil
}

// Native manifest contract constants. These mirror pkg/pluginhost/contract.go
// and must stay in sync; the host's ValidateNativeManifest enforces them.
const (
	NativeRuntime       = "native"
	BinaryCodecV1       = "binarycodec-v1"
	IsolationInProcess  = "inprocess"
	IsolationSubprocess = "subprocess"
	TrustFirstParty     = "first_party"
	// ProtocolVersion2 is the subprocess frame protocol this SDK speaks:
	// correlated full-duplex frames (callID in the header), matching the
	// host's v2-only codec (pkg/pluginhost/contract.go HostProtocolVersion).
	ProtocolVersion2 = int32(2)
	ContractVersion1 = "1"
	// Version is this SDK's semver. Plugins generated/vendored with it stamp
	// it into their manifest SdkVersion; the plugin store filters entries by
	// SdkVersion major equality + minor.patch <= the host's SDK version.
	Version = "0.3.1"
	// DefaultSigner is the signer identity applied to first-party native
	// plugins built with this SDK. Native builds run in-process under the
	// trusted host, so the signer is a well-known first-party constant
	// rather than a per-plugin signing key.
	DefaultSigner = "sporemind.first-party"
)

// BundleTool declares a single tool entry within a bundle, carrying the
// runtime declaration set (effect/service/toolName/stream) for discovery
// catalog alignment.
type BundleTool struct {
	CallableID string `json:"CallableId"`
	Effect     string `json:"Effect,omitempty"`
	Service    string `json:"Service,omitempty"`
	ToolName   string `json:"ToolName,omitempty"`
	Stream     bool   `json:"Stream,omitempty"`
}

// Bundle is a named grouping of tools that an app exposes as a discoverable
// protocol asset. The directory service aggregates bundles from all providers.
type Bundle struct {
	Title       string       `json:"Title"`
	Description string       `json:"Description,omitempty"`
	Tools       []BundleTool `json:"Tools"`
}

// Manifest describes a plugin's identity, capabilities, and entrypoints.
// JSON tags match the schema-defined AppManifest contract (PascalCase) so the
// manifest JSON produced by WriteManifest is directly accepted by the host's
// ValidateNativeManifest.
type Manifest struct {
	ID              string   `json:"Id"`
	Name            string   `json:"Name"`
	Version         string   `json:"Version"`
	Runtime         string   `json:"Runtime,omitempty"`
	ProtocolVersion int32    `json:"ProtocolVersion,omitempty"`
	// SdkVersion is the SDK semver this plugin was built with. Normalize
	// stamps the vendored SDK's Version when omitted, so manifests always
	// carry it; the plugin store uses it for host-compat filtering.
	SdkVersion  string   `json:"SdkVersion,omitempty"`
	Namespace   string   `json:"Namespace,omitempty"`
	Permissions []string `json:"Permissions,omitempty"`
	// Listens are the host event kinds the plugin subscribes to (appdef
	// `listen <kind> {}`); the pluginhost fans matching bus events into
	// RegisterEventListener handlers under `__event__:<kind>`.
	Listens     []string     `json:"Listens,omitempty"`
	Callables   []Callable   `json:"Callables,omitempty"`
	Entrypoints []Entrypoint `json:"Entrypoints,omitempty"`
	Bundles     []Bundle     `json:"Bundles,omitempty"`
}

// Callable declares a host-visible callable with request/response schemas.
type Callable struct {
	ID             string `json:"Id"`
	// Description flows from the .appdef doc-comment above the callable
	// block; shown in the PluginToolbar capability panel. Mirrors
	// AppCallableDescriptor.Description on the host schema side.
	Description    string `json:"Description,omitempty"`
	RequestSchema  string `json:"RequestSchema"`
	ResponseSchema string `json:"ResponseSchema"`
	Effect         string `json:"Effect,omitempty"`
	Service        string `json:"Service,omitempty"`
	ToolName       string `json:"ToolName,omitempty"`
	Streaming      bool   `json:"Streaming,omitempty"`
	TimeoutMs      int64  `json:"TimeoutMs,omitempty"`
	// Expose controls which consumer surfaces may call this callable:
	// "frontend", "agent", or "both". Empty defaults to "both".
	Expose string `json:"Expose,omitempty"`
	// Watch lists event IDs whose emission invalidates cached results.
	Watch []string `json:"Watch,omitempty"`
}

// Entrypoint declares a UI surface provided by the plugin.
type Entrypoint struct {
	Kind  string `json:"Kind"` // page | panel | command | settings | tool
	ID    string `json:"Id"`
	Title string `json:"Title"`
	Route string `json:"Route,omitempty"`
}

// Normalize fills in default values for fields the developer may omit.
// Runtime defaults to "native", ProtocolVersion to 2, Namespace to ID,
// SdkVersion to the SDK's own Version.
func (m Manifest) Normalize() Manifest {
	if m.Runtime == "" {
		m.Runtime = NativeRuntime
	}
	if m.ProtocolVersion == 0 {
		m.ProtocolVersion = ProtocolVersion2
	}
	if m.SdkVersion == "" {
		m.SdkVersion = Version
	}
	if m.Namespace == "" {
		m.Namespace = m.ID
	}
	return m
}

// ToAppManifest converts the SDK Manifest to the schema-generated AppManifest
// type, applying defaults and validating required fields. The returned value
// is directly compatible with the host's ValidateNativeManifest.
func (m Manifest) ToAppManifest() (gen.AppManifest, error) {
	m = m.Normalize()
	if m.ID == "" || m.Name == "" || m.Version == "" {
		return gen.AppManifest{}, fmt.Errorf("manifest: Id, Name, and Version are required")
	}
	if m.Runtime != NativeRuntime {
		return gen.AppManifest{}, fmt.Errorf("manifest: Runtime must be %q for native plugins", NativeRuntime)
	}
	callables := make([]gen.AppCallableDescriptor, 0, len(m.Callables))
	for _, c := range m.Callables {
		if c.ID == "" || c.RequestSchema == "" || c.ResponseSchema == "" {
			return gen.AppManifest{}, fmt.Errorf("manifest: callable is incomplete (Id, RequestSchema, ResponseSchema required)")
		}
		if c.ToolName != "" {
			if err := ValidateToolName(c.ToolName); err != nil {
				return gen.AppManifest{}, fmt.Errorf("manifest: callable %q: %w", c.ID, err)
			}
		}
		callables = append(callables, gen.AppCallableDescriptor{
			ID:             c.ID,
			RequestSchema:  c.RequestSchema,
			ResponseSchema: c.ResponseSchema,
			Effect:         c.Effect,
			Service:        c.Service,
			ToolName:       c.ToolName,
			Streaming:      c.Streaming,
			Expose:         c.Expose,
			Watch:          c.Watch,
		})
	}
	entrypoints := make([]gen.AppEntrypoint, 0, len(m.Entrypoints))
	for _, e := range m.Entrypoints {
		entrypoints = append(entrypoints, gen.AppEntrypoint{
			Kind: e.Kind, ID: e.ID, Title: e.Title, Route: e.Route,
		})
	}
	var bundles []gen.AppBundle
	if len(m.Bundles) > 0 {
		bundles = make([]gen.AppBundle, 0, len(m.Bundles))
		for _, b := range m.Bundles {
			if b.Title == "" {
				return gen.AppManifest{}, fmt.Errorf("manifest: bundle title is required")
			}
			tools := make([]gen.AppBundleTool, 0, len(b.Tools))
			for _, t := range b.Tools {
				if t.CallableID == "" {
					return gen.AppManifest{}, fmt.Errorf("manifest: bundle tool CallableId is required")
				}
				tools = append(tools, gen.AppBundleTool{
					CallableID: t.CallableID,
					Effect:     t.Effect,
					Service:    t.Service,
					ToolName:   t.ToolName,
					Stream:     t.Stream,
				})
			}
			bundles = append(bundles, gen.AppBundle{
				Title:       b.Title,
				Description: b.Description,
				Tools:       tools,
			})
		}
	}
	return gen.AppManifest{
		ID:              m.ID,
		Name:            m.Name,
		Version:         m.Version,
		Runtime:         m.Runtime,
		ProtocolVersion: m.ProtocolVersion,
		SdkVersion:      m.SdkVersion,
		Namespace:       m.Namespace,
		Permissions:     m.Permissions,
		Listens:         m.Listens,
		Callables:       callables,
		Entrypoints:     entrypoints,
		Bundles:         bundles,
	}, nil
}

// DefaultAbi returns a PluginAbi that satisfies the host's native contract.
// Native builds performed by the host are first-party and in-process, so the
// ABI carries the well-known signer identity.
func DefaultAbi() gen.PluginAbi {
	return gen.PluginAbi{
		Name:            "spore-plugin",
		Version:         1,
		Encoding:        BinaryCodecV1,
		InvokeSymbol:    "PluginInvoke",
		ContractVersion: ContractVersion1,
		Isolation:       IsolationInProcess,
		TrustClass:      TrustFirstParty,
		Signer:          DefaultSigner,
	}
}

// Permission constants used by the host to check capability access. These
// mirror pkg/appbinding/security.go — the host capability catalog is the
// authoritative vocabulary; a capability string outside this set is rejected
// at policy-load and registration-validation time (deny-all default).
const (
	PermLLMInvoke      = "llm.invoke"
	PermFSRead         = "fs.read"
	PermFSWrite        = "fs.write"
	PermShellExec      = "shell.exec"
	PermConfigRead     = "config.read"
	PermProviderRead   = "provider.read"
	PermAggregatorRead = "aggregator.read"
	PermAppState       = "app.state"
	PermAppData        = "app.data"
	PermAppEmit        = "app.emit"
	PermRegistryRead   = "registry.read"
	PermAgentObserve   = "agent.observe"
)
