// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "../../../gospore/gateway/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as buildinfo$0 from "../buildinfo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gen$0 from "../domain/gen/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logging$0 from "../logging/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AckCrashRecords marks the given crash records as acknowledged so they stop
 * being reported on subsequent startups.
 */
export function AckCrashRecords(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(2634891638, ids);
}

/**
 * BeforeClose persists the latest observed window geometry. The reactive
 * observers in RecordWindowGeometry keep winState current, so this only
 * cancels any pending debounced write and flushes synchronously to
 * guarantee the save completes before the window is destroyed.
 */
export function BeforeClose(): $CancellablePromise<void> {
    return $Call.ByID(2494002969);
}

/**
 * Bind wires the Wails v3 application handle so the service can reach the
 * event/dialog/clipboard/browser managers. Called from main.go after
 * application.New but before app.Run.
 */
export function Bind(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3072337839, app);
}

/**
 * BootCrashReport returns how the previous session ended. Called by the
 * frontend once per webview load, so the dynamic parts are re-derived from the
 * crash store: acknowledged records and error-tail lines stay dismissed
 * instead of replaying the boot-time snapshot on every refresh.
 */
export function BootCrashReport(): $CancellablePromise<$models.BootCrashReport | null> {
    return $Call.ByID(3969604957).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BrowserHistoryBack navigates the session's child browser window back
 * one entry in its native WebView2 history stack.
 */
export function BrowserHistoryBack(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4237876195, sessionID);
}

/**
 * BrowserHistoryForward navigates the session's child browser window
 * forward one entry in its native WebView2 history stack.
 */
export function BrowserHistoryForward(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(713934565, sessionID);
}

/**
 * CaptureBrowserWindow captures the current on-screen content of a
 * session's child browser window and returns it as a data: URL. Used so the
 * frontend can show a frozen snapshot while the real window is temporarily
 * hidden (e.g. for dropdown menus).
 */
export function CaptureBrowserWindow(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(682031730, sessionID);
}

/**
 * CheckUpdate fetches the channel's latest.json and resolves whether a newer
 * build exists. Safe to call concurrently — the updater collapses in-flight
 * checks. Bound to the frontend via Wails v3.
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(1649302433).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CloseBrowserSession closes and destroys a session's child browser window.
 * It does NOT remove the persisted browser instance — closing a tab only
 * hides the window. The frontend separately calls closeBrowserInstance to
 * set Open=false so the instance survives and can be reopened later.
 */
export function CloseBrowserSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2220247536, sessionID);
}

/**
 * CloseScreenshotWindow closes the screenshot overlay window and clears data.
 */
export function CloseScreenshotWindow(): $CancellablePromise<void> {
    return $Call.ByID(3304147444);
}

export function DesktopWindowState(): $CancellablePromise<domain$0.DesktopWindowState> {
    return $Call.ByID(3971789617).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DestroyAllBrowserWindows closes and removes every browser session.
 * Called on frontend startup to clean up any child windows left over from
 * a previous run or a hot-reload.
 */
export function DestroyAllBrowserWindows(): $CancellablePromise<void> {
    return $Call.ByID(3372743272);
}

/**
 * DismissUpdate clears the available flag for the current remote version so
 * the button stops pulsing; the download stays cached. Bound to the frontend.
 */
export function DismissUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3455950061);
}

/**
 * DownloadUpdate fetches the remote installer into the OS download folder and
 * verifies its sha256. Progress is emitted on the "sporemind:update" event.
 * Bound to the frontend via Wails v3.
 */
export function DownloadUpdate(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(2879446761).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * EvalJSResult is the Wails binding that the injected JavaScript calls back
 * into after executing a script. It delivers the JSON-serialised result to the
 * waiting evalJS call via a channel.
 */
export function EvalJSResult(id: string, result: string): $CancellablePromise<void> {
    return $Call.ByID(63417644, id, result);
}

/**
 * FocusMainWindow re-activates the main window. Invoked in the first instance
 * when a second instance launches (Wails SingleInstance).
 */
export function FocusMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(496601189);
}

/**
 * GetAdminToken returns a JWT for the local admin account. Wails uses this
 * to auto-login on startup without a password — the desktop binary lives
 * in the same process as the user actor, so anything that can call this
 * already has process-level trust.
 * 
 * The token issuer is exposed by the user actor as a typed resource at
 * startup; this method is just a thin lookup that never crosses the
 * transport boundary.
 * 
 * The Wails frontend may call this binding before the actor tree finished
 * starting (the binding bypasses the mailbox, so the registry-freeze
 * ordering guarantee does not apply) — the lookup therefore waits, bounded,
 * for the user actor to publish the issuer instead of failing instantly.
 */
export function GetAdminToken(): $CancellablePromise<string> {
    return $Call.ByID(959935448);
}

/**
 * GetBrowserPageSnapshot injects a reader script into the browser window, waits
 * for the page data to arrive via postMessage, and returns it. This lets the
 * frontend inspect the DOM text, cookies, and web storage of any open instance.
 */
export function GetBrowserPageSnapshot(id: string): $CancellablePromise<$models.BrowserPageSnapshot> {
    return $Call.ByID(2806196127, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetBuildInfo returns the build metadata snapshot for the current binary.
 * Bound to the frontend via Wails v3 `wails3 generate bindings -ts`.
 */
export function GetBuildInfo(): $CancellablePromise<buildinfo$0.Info> {
    return $Call.ByID(229763848).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetConsoleLogs returns the most recent persisted console log entries.
 */
export function GetConsoleLogs(limit: number): $CancellablePromise<logging$0.ConsoleEntry[]> {
    return $Call.ByID(2878256414, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetDesktopTransport returns the configured desktop transport mode
 * ("wails" or "ws"). Used by the frontend to decide which transport to
 * create on startup.
 */
export function GetDesktopTransport(): $CancellablePromise<string> {
    return $Call.ByID(1934355169);
}

/**
 * GetFeatureFlags returns the feature flags gated by the current build type.
 * Bound to the frontend via Wails v3 `wails3 generate bindings -ts`.
 */
export function GetFeatureFlags(): $CancellablePromise<buildinfo$0.FeatureFlags> {
    return $Call.ByID(3366584797).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetGatewayAddr exposes the gateway host:port to the frontend so the
 * WebSocket client can target the in-process gateway even when
 * sporemind.yaml overrides the default :18080.
 */
export function GetGatewayAddr(): $CancellablePromise<string> {
    return $Call.ByID(1756090761);
}

/**
 * GetGatewayBindAddrs returns the extra gateway bind addresses configured
 * in sporemind.yaml. Empty when LAN access is off.
 */
export function GetGatewayBindAddrs(): $CancellablePromise<string[]> {
    return $Call.ByID(3125158047).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetLocalIPv4 returns the best candidate local IPv4 address for LAN access,
 * or an empty string if none is available. Exposed so the frontend can bind
 * the gateway to a specific LAN IP instead of 0.0.0.0.
 */
export function GetLocalIPv4(): $CancellablePromise<string> {
    return $Call.ByID(2219999692);
}

/**
 * GetLocalNetworkGatewayURL returns an http:// URL that a phone on the same
 * local network can use to reach the gateway. It prefers the first non-loopback
 * IPv4 address and falls back to an empty string if none is available.
 */
export function GetLocalNetworkGatewayURL(): $CancellablePromise<string> {
    return $Call.ByID(2164930520);
}

/**
 * GetLogs returns the most recent backend log entries.
 */
export function GetLogs(limit: number): $CancellablePromise<gateway$0.LogEntry[]> {
    return $Call.ByID(3622924255, limit).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetLogsBefore returns up to limit backend log entries older than before.
 * The before timestamp is RFC3339Nano; entries with an equal timestamp are
 * excluded so the caller can use the oldest already-loaded entry as a cursor.
 * If the ring does not contain enough older entries, the file store is queried.
 */
export function GetLogsBefore(before: string, limit: number): $CancellablePromise<gateway$0.LogEntry[]> {
    return $Call.ByID(3873348136, before, limit).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetRawGatewayAddr returns the effective gateway address — the env override
 * or the flavor-remapped config value (e.g. ":18080"; devrelease builds
 * report 18081), not necessarily the literal sporemind.yaml text. Used by
 * the developer settings form.
 */
export function GetRawGatewayAddr(): $CancellablePromise<string> {
    return $Call.ByID(1994476151);
}

/**
 * GetScreenshotData returns the data captured by the most recent StartScreenshot.
 */
export function GetScreenshotData(): $CancellablePromise<$models.ScreenshotData | null> {
    return $Call.ByID(3769772216).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetStorageSettings returns the storage settings for the settings UI.
 * Backend fields are the raw yaml values ("" = follow the default); the
 * retention fields carry the effective values with defaults applied.
 */
export function GetStorageSettings(): $CancellablePromise<$models.StorageSettings> {
    return $Call.ByID(2679214336).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetUpdateStatus returns the current updater snapshot. Bound to the frontend.
 */
export function GetUpdateStatus(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(1412544815).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * HideAllBrowserWindows hides every browser session immediately, regardless of
 * its wanted state, and raises the persistent overlay suppression so sessions
 * created or first-painted while the overlay is open (e.g. the boot-time tab
 * restore racing the crash overlay) stay hidden too. Driven only by the
 * frontend BrowserOverlayManager when the first HTML overlay opens.
 */
export function HideAllBrowserWindows(): $CancellablePromise<void> {
    return $Call.ByID(2653081622);
}

/**
 * InstallUpdate launches the downloaded installer and quits so it can replace
 * the running binary. Requires the download to be ready (sha256 verified).
 * Bound to the frontend via Wails v3.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2437144554);
}

/**
 * Log appends a structured log entry and emits it to the frontend.
 */
export function Log(level: string, msg: string, caller: string, fields: { [_ in string]?: any }): $CancellablePromise<gateway$0.LogEntry> {
    return $Call.ByID(1312406826, level, msg, caller, fields).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * NavigateBrowserSession changes the URL of a session's child browser window.
 * 
 * Contract §4: when the session or its window does not exist (session==nil or
 * window==nil) it MUST create the session and then load url — equivalent to the
 * Open path — rather than silently returning. This is the basis of the empty-tab
 * first-navigation fix: an agent/API call or any non-BrowserView caller that
 * navigates a session that was never opened now creates it (reusing the Open
 * creation path, which performs its own beginHostNavigation(navSourceOpen)).
 * 
 * For an existing window it allocates a host pending (contract §2.5.1/§2.5.3)
 * BEFORE invoking the tokenized primitive, so the session enters loading and the
 * pending can be bound when the adapter's NavigationStarting carries the
 * commandToken. It uses the tokenized host primitives (contract §8): SetURL for a
 * new URL, Reload for the same URL. ExecJS(window.location.href/reload) is
 * forbidden for host navigation because it carries commandToken 0 and would be
 * misclassified as a page-initiated navigation, losing host correlation. The
 * navigation flows through the native NavigationStarting/Completed lifecycle, so
 * confirmedURL is set exclusively by the commit — the address bar is never
 * optimistically updated here.
 */
export function NavigateBrowserSession(sessionID: string, url: string): $CancellablePromise<void> {
    return $Call.ByID(2240011171, sessionID, url);
}

/**
 * OpenBrowserSession creates or reuses a child Wails window for the given
 * session and positions it over the right panel tab area. kind determines the
 * user-data profile: "global" (shared singleton), "independent" (isolated),
 * or "app" (plugin page).
 */
export function OpenBrowserSession(sessionID: string, kind: string, url: string, x: number, y: number, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(2334173268, sessionID, kind, url, x, y, width, height);
}

export function OpenDevTools(): $CancellablePromise<void> {
    return $Call.ByID(2133331398);
}

/**
 * OpenSystemLogin opens the sporemind login page in the system default
 * browser and starts the local callback server (if not already running) to
 * receive the OAuth redirect. An empty loginURL opens the configured sporemind
 * login page (config.SporemindLoginURL). It returns an error if the callback
 * server cannot be started or the browser cannot be opened.
 */
export function OpenSystemLogin(loginURL: string): $CancellablePromise<void> {
    return $Call.ByID(1633922870, loginURL);
}

/**
 * RawMessageHandler returns the Wails v3 RawMessageHandler closure that feeds
 * frontend raw messages into the gospore gateway via a strictly-ordered queue.
 */
export function RawMessageHandler(): $CancellablePromise<any> {
    return $Call.ByID(731422875);
}

/**
 * RecordWindowGeometry samples the live window bounds and schedules a
 * debounced save. Called from WindowDidMove / DidResize / Maximise /
 * UnMaximise / Restore handlers so the latest normal bounds are always
 * on disk. This is necessary because the BeforeClose hook races with
 * Wails v3's internal close listener, which marks the window destroyed
 * before user listeners run — at which point Width/Height/Position/
 * IsMaximised all return zero.
 */
export function RecordWindowGeometry(): $CancellablePromise<void> {
    return $Call.ByID(1987480801);
}

export function RefreshScreenshotForWindow(handle: number): $CancellablePromise<$models.ScreenshotData | null> {
    return $Call.ByID(2538944262, handle).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * RevealUpdateInFolder opens the OS file manager with the downloaded
 * installer selected. Bound to the frontend via Wails v3.
 */
export function RevealUpdateInFolder(): $CancellablePromise<void> {
    return $Call.ByID(388142951);
}

/**
 * SaveConfig persists the current in-memory configuration to sporemind.yaml.
 */
export function SaveConfig(): $CancellablePromise<void> {
    return $Call.ByID(874578775);
}

export function SaveDesktopWindowState(state: domain$0.DesktopWindowState): $CancellablePromise<void> {
    return $Call.ByID(3425264348, state);
}

/**
 * SaveScreenshotDialog opens a save dialog and writes the provided base64 image.
 */
export function SaveScreenshotDialog(base64Data: string, defaultName: string): $CancellablePromise<void> {
    return $Call.ByID(2876497573, base64Data, defaultName);
}

/**
 * SelectAppPackageFile opens a file picker filtered to .zip app packages.
 * Windows IFileDialog cannot pick files and folders in one dialog
 * (FOS_PICKFOLDERS greys out files), so the install flow uses one picker
 * per source kind.
 */
export function SelectAppPackageFile(): $CancellablePromise<$models.InstallSourceSelection> {
    return $Call.ByID(2212415167).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SelectAppPackageFolder opens a folder-only picker for a package directory.
 */
export function SelectAppPackageFolder(): $CancellablePromise<$models.InstallSourceSelection> {
    return $Call.ByID(1386660473).then(($result: any) => {
        return $$createType15($result);
    });
}

export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(2200094150);
}

export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(822988308);
}

/**
 * SetBootCrashReport wires the previous session's crash scan result.
 * Called from main after application.New, before any window exists.
 */
export function SetBootCrashReport(r: $models.BootCrashReport | null): $CancellablePromise<void> {
    return $Call.ByID(2926270589, r);
}

/**
 * SetBrowserColorScheme updates the preferred color scheme of every
 * right-panel browser window so pages honour prefers-color-scheme. mode is
 * "light" or "dark".
 */
export function SetBrowserColorScheme(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3342852228, mode);
}

/**
 * SetBrowserWindowVisible shows or hides a session's child browser window
 * without destroying it, so state is preserved when switching tabs.
 */
export function SetBrowserWindowVisible(sessionID: string, visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(188275326, sessionID, visible);
}

/**
 * SetClipboardImage decodes a data:image/png;base64,... URL and writes the image
 * to the system clipboard in two formats:
 *   - CF_DIB  — for pasting into Paint, Word, etc.
 *   - CF_HDROP — for pasting as a file in Explorer
 */
export function SetClipboardImage(dataURL: string): $CancellablePromise<void> {
    return $Call.ByID(452409947, dataURL);
}

/**
 * SetClipboardText writes text to the system clipboard.
 */
export function SetClipboardText(text: string): $CancellablePromise<void> {
    return $Call.ByID(3155371909, text);
}

/**
 * SetDesktopTransport updates the in-memory desktop transport mode. Valid
 * values are "wails" and "ws". The change is persisted to sporemind.yaml
 * by SaveConfig.
 */
export function SetDesktopTransport(transport: string): $CancellablePromise<void> {
    return $Call.ByID(3117269381, transport);
}

/**
 * SetGatewayAddr updates the in-memory gateway address. The change is
 * persisted to sporemind.yaml by SaveConfig.
 */
export function SetGatewayAddr(addr: string): $CancellablePromise<void> {
    return $Call.ByID(2177955797, addr);
}

/**
 * SetGatewayBindAddrs updates the in-memory extra gateway bind addresses.
 * Each address gets its own listener at runtime, enabling dual binding
 * (loopback + LAN IP) without 0.0.0.0. Persisted by SaveConfig.
 */
export function SetGatewayBindAddrs(addrs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1364874723, addrs);
}

/**
 * SetStorageSettings validates and applies the settings-UI storage form to
 * the in-memory config. Callers persist with SaveConfig. Invalid backend
 * values are rejected with an error — never a silent fallback.
 */
export function SetStorageSettings(s: $models.StorageSettings): $CancellablePromise<void> {
    return $Call.ByID(151372804, s);
}

/**
 * SetWindow wires the primary webview window. Called from main.go after the
 * window is created but before app.Run so ServiceStartup can use it.
 */
export function SetWindow(win: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(2782444260, win);
}

/**
 * ShowAllBrowserWindows clears the overlay suppression and re-applies the
 * sessions' wanted state. Driven by the frontend BrowserOverlayManager when the
 * last HTML overlay closes.
 */
export function ShowAllBrowserWindows(): $CancellablePromise<void> {
    return $Call.ByID(2937770573);
}

/**
 * ShowScreenshotWindow reveals the previously hidden screenshot window
 * once the frontend has loaded the image, for a seamless visual transition.
 * The window is created asynchronously in StartScreenshot; poll briefly if
 * it hasn't been created yet.
 */
export function ShowScreenshotWindow(): $CancellablePromise<void> {
    return $Call.ByID(931014285);
}

/**
 * Shutdown cancels the gospore context and waits for the actor tree to stop.
 * Called from Wails OnShutdown so the process exits when the window closes.
 * If the actor tree does not stop within 5s the process is force-killed.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(882366450);
}

/**
 * StartFileDragOut starts a native OS drag-out: the given files/folders are
 * offered to whatever drop target (Explorer, desktop, another app) the user
 * drops them on, using a copy-only native drag. The call blocks until the
 * drag completes (drop, or cancel via Esc / button release outside a target);
 * cancelling the drag is a success, not an error. Dragging out extracted
 * archives cleans up the temp directory afterwards.
 */
export function StartFileDragOut(req: $models.FileDragOutRequest): $CancellablePromise<void> {
    return $Call.ByID(3442909712, req);
}

/**
 * StartScreenshot captures all visible windows and the full screen, then opens
 * a new borderless, always-on-top, fullscreen window for the screenshot editor.
 */
export function StartScreenshot(): $CancellablePromise<$models.ScreenshotData | null> {
    return $Call.ByID(4259582160).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * UpdateBrowserWindow resizes and repositions the child browser window for
 * the given session. Coordinates are relative to the main window's client area.
 */
export function UpdateBrowserWindow(sessionID: string, x: number, y: number, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(4096443179, sessionID, x, y, width, height);
}

/**
 * WaitGatewayReady blocks until the in-process gateway listener is accepting
 * connections, or the given timeout (ms) elapses. The HTTP listener binds only
 * after every actor finished OnStart, so a ws-transport frontend that dials
 * before this returns gets connection-refused and lands in the client's
 * 0.5–1.5s reconnect backoff — the dominant part of the ws-vs-wails startup
 * gap. Returns true when the gateway is (already) accepting.
 */
export function WaitGatewayReady(timeoutMs: number): $CancellablePromise<boolean> {
    return $Call.ByID(2908900900, timeoutMs);
}

/**
 * WriteConsoleLog persists a frontend console log entry.
 */
export function WriteConsoleLog(level: string, message: string, location: string, ts: number): $CancellablePromise<void> {
    return $Call.ByID(3033754782, level, message, location, ts);
}

// Private type creation functions
const $$createType0 = $models.BootCrashReport.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.UpdateStatus.createFrom;
const $$createType3 = gen$0.DesktopWindowState.createFrom;
const $$createType4 = $models.BrowserPageSnapshot.createFrom;
const $$createType5 = buildinfo$0.Info.createFrom;
const $$createType6 = logging$0.ConsoleEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = buildinfo$0.FeatureFlags.createFrom;
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = gateway$0.LogEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.ScreenshotData.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.StorageSettings.createFrom;
const $$createType15 = $models.InstallSourceSelection.createFrom;
