// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppUpdateMeta is the shape published by scripts/publish-release.mjs at
 * releases/{channel}/latest.json on the R2 release bucket.
 */
export class AppUpdateMeta {
    "public_version": string;
    "channel": string;
    "platform": string;
    "file": string;
    "url": string;
    "sha256": string;
    "size": number;
    "notes": string;

    /** Creates a new AppUpdateMeta instance. */
    constructor($$source: Partial<AppUpdateMeta> = {}) {
        if (!("public_version" in $$source)) {
            this["public_version"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppUpdateMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): AppUpdateMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppUpdateMeta($$parsedSource as Partial<AppUpdateMeta>);
    }
}

/**
 * BootCrashReport describes how the previous session ended. The frontend
 * fetches it once at startup and renders a crash notice when non-empty.
 */
export class BootCrashReport {
    "abnormalExit": boolean;
    "previousSession"?: CrashSessionInfo | null;
    "records": CrashRecordInfo[];
    "errorsTail"?: string[];
    "logTail"?: string[];

    /** Creates a new BootCrashReport instance. */
    constructor($$source: Partial<BootCrashReport> = {}) {
        if (!("abnormalExit" in $$source)) {
            this["abnormalExit"] = false;
        }
        if (!("records" in $$source)) {
            this["records"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootCrashReport instance from a string or object.
     */
    static createFrom($$source: any = {}): BootCrashReport {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("previousSession" in $$parsedSource) {
            $$parsedSource["previousSession"] = $$createField1_0($$parsedSource["previousSession"]);
        }
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField2_0($$parsedSource["records"]);
        }
        if ("errorsTail" in $$parsedSource) {
            $$parsedSource["errorsTail"] = $$createField3_0($$parsedSource["errorsTail"]);
        }
        if ("logTail" in $$parsedSource) {
            $$parsedSource["logTail"] = $$createField4_0($$parsedSource["logTail"]);
        }
        return new BootCrashReport($$parsedSource as Partial<BootCrashReport>);
    }
}

/**
 * BrowserPageSnapshot is the DTO returned to the frontend.
 */
export class BrowserPageSnapshot {
    "url": string;
    "title": string;
    "text": string;
    "cookies": string;
    "local_storage": { [_ in string]?: string };
    "session_storage": { [_ in string]?: string };

    /** Creates a new BrowserPageSnapshot instance. */
    constructor($$source: Partial<BrowserPageSnapshot> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("cookies" in $$source)) {
            this["cookies"] = "";
        }
        if (!("local_storage" in $$source)) {
            this["local_storage"] = {};
        }
        if (!("session_storage" in $$source)) {
            this["session_storage"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserPageSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserPageSnapshot {
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("local_storage" in $$parsedSource) {
            $$parsedSource["local_storage"] = $$createField4_0($$parsedSource["local_storage"]);
        }
        if ("session_storage" in $$parsedSource) {
            $$parsedSource["session_storage"] = $$createField5_0($$parsedSource["session_storage"]);
        }
        return new BrowserPageSnapshot($$parsedSource as Partial<BrowserPageSnapshot>);
    }
}

/**
 * CrashRecordInfo is one crash artifact surfaced to the frontend at boot.
 */
export class CrashRecordInfo {
    "id": string;
    "kind": string;
    "time": string;
    "pid"?: number;
    "summary": string;
    "detail"?: string;
    "dumpFile"?: string;

    /** Creates a new CrashRecordInfo instance. */
    constructor($$source: Partial<CrashRecordInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrashRecordInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CrashRecordInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CrashRecordInfo($$parsedSource as Partial<CrashRecordInfo>);
    }
}

/**
 * CrashSessionInfo is the live-session marker. Its presence at startup means
 * the previous process never reached a clean shutdown.
 */
export class CrashSessionInfo {
    "pid": number;
    "startedAt": string;
    "version"?: string;

    /** Creates a new CrashSessionInfo instance. */
    constructor($$source: Partial<CrashSessionInfo> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrashSessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CrashSessionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CrashSessionInfo($$parsedSource as Partial<CrashSessionInfo>);
    }
}

/**
 * FileDragOutRequest is the payload of the StartFileDragOut binding. At least
 * one source must be provided: LocalPaths, ArchiveTarGzBase64, or both.
 */
export class FileDragOutRequest {
    /**
     * LocalPaths are absolute local file or directory paths to drag out as-is.
     */
    "localPaths": string[];

    /**
     * ArchiveTarGzBase64, when non-empty, is a tar.gz archive (standard
     * base64). It is extracted to a temp directory and the resulting folder is
     * dragged out together with LocalPaths. Entries with absolute paths or
     * ".." traversal components are rejected.
     */
    "archiveTarGzBase64": string;

    /**
     * ArchiveRootName is the folder name under which the archive is
     * extracted (the name the drop target sees). It must be a single path
     * component. Defaults to "sporemind-dragout" when empty.
     */
    "archiveRootName": string;

    /** Creates a new FileDragOutRequest instance. */
    constructor($$source: Partial<FileDragOutRequest> = {}) {
        if (!("localPaths" in $$source)) {
            this["localPaths"] = [];
        }
        if (!("archiveTarGzBase64" in $$source)) {
            this["archiveTarGzBase64"] = "";
        }
        if (!("archiveRootName" in $$source)) {
            this["archiveRootName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDragOutRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): FileDragOutRequest {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localPaths" in $$parsedSource) {
            $$parsedSource["localPaths"] = $$createField0_0($$parsedSource["localPaths"]);
        }
        return new FileDragOutRequest($$parsedSource as Partial<FileDragOutRequest>);
    }
}

/**
 * InstallSourceSelection is the result of an install picker: the chosen path
 * plus whether it points at a package directory (true) or a regular file such
 * as a .zip package (false). Empty Path means cancelled.
 */
export class InstallSourceSelection {
    "Path": string;
    "IsDir": boolean;

    /** Creates a new InstallSourceSelection instance. */
    constructor($$source: Partial<InstallSourceSelection> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("IsDir" in $$source)) {
            this["IsDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallSourceSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallSourceSelection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallSourceSelection($$parsedSource as Partial<InstallSourceSelection>);
    }
}

/**
 * ScreenshotData holds the screenshot image and window list.
 */
export class ScreenshotData {
    "ImageBase64": string;
    "Windows": WindowInfo[];

    /** Creates a new ScreenshotData instance. */
    constructor($$source: Partial<ScreenshotData> = {}) {
        if (!("ImageBase64" in $$source)) {
            this["ImageBase64"] = "";
        }
        if (!("Windows" in $$source)) {
            this["Windows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenshotData instance from a string or object.
     */
    static createFrom($$source: any = {}): ScreenshotData {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Windows" in $$parsedSource) {
            $$parsedSource["Windows"] = $$createField1_0($$parsedSource["Windows"]);
        }
        return new ScreenshotData($$parsedSource as Partial<ScreenshotData>);
    }
}

/**
 * StorageSettings is the settings-UI view of the storage configuration:
 * scoped backends (raw yaml values — "" follows the goleveldb default) and
 * retention windows (effective values with defaults applied). Backend and
 * retention changes take effect after a restart; persisting to yaml happens
 * via SetStorageSettings + SaveConfig.
 */
export class StorageSettings {
    /**
     * Raw backend_aistats value: "" (default goleveldb) / "fs" / "goleveldb".
     */
    "backendAistats": string;

    /**
     * Raw backend_logs value: "" (default goleveldb) / "fs" / "goleveldb".
     */
    "backendLogs": string;

    /**
     * Effective backend-log retention window in days.
     */
    "logsRetentionDays": number;

    /**
     * Effective raw aistats record retention window in days.
     */
    "aistatsRawDays": number;

    /**
     * Effective daily-rollup aistats retention window in days.
     */
    "aistatsDailyDays": number;

    /** Creates a new StorageSettings instance. */
    constructor($$source: Partial<StorageSettings> = {}) {
        if (!("backendAistats" in $$source)) {
            this["backendAistats"] = "";
        }
        if (!("backendLogs" in $$source)) {
            this["backendLogs"] = "";
        }
        if (!("logsRetentionDays" in $$source)) {
            this["logsRetentionDays"] = 0;
        }
        if (!("aistatsRawDays" in $$source)) {
            this["aistatsRawDays"] = 0;
        }
        if (!("aistatsDailyDays" in $$source)) {
            this["aistatsDailyDays"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): StorageSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageSettings($$parsedSource as Partial<StorageSettings>);
    }
}

/**
 * UpdateStatus is the snapshot handed to the frontend and emitted on the
 * "sporemind:update" Wails event. It mirrors the frontend state machine:
 * 
 * 	Phase ""               — never checked / disabled
 * 	Phase "checking"       — check in flight
 * 	Phase "idle"           — checked, no update
 * 	Phase "available"      — newer version on the channel
 * 	Phase "downloading"    — DownloadUpdate in flight (Progress 0..100)
 * 	Phase "ready"          — downloaded + sha256 verified, ready to install
 * 	Phase "error"          — Error carries the failure
 */
export class UpdateStatus {
    "phase": string;
    "current_version": string;
    "channel": string;
    "update_available": boolean;
    "remote"?: AppUpdateMeta | null;
    "progress": number;
    "path": string;
    "error": string;

    /** Creates a new UpdateStatus instance. */
    constructor($$source: Partial<UpdateStatus> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }
        if (!("update_available" in $$source)) {
            this["update_available"] = false;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateStatus {
        const $$createField4_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("remote" in $$parsedSource) {
            $$parsedSource["remote"] = $$createField4_0($$parsedSource["remote"]);
        }
        return new UpdateStatus($$parsedSource as Partial<UpdateStatus>);
    }
}

/**
 * WindowInfo represents a captured application window.
 */
export class WindowInfo {
    "Handle": number;
    "Title": string;
    "X": number;
    "Y": number;
    "Width": number;
    "Height": number;
    "ZOrder": number;

    /** Creates a new WindowInfo instance. */
    constructor($$source: Partial<WindowInfo> = {}) {
        if (!("Handle" in $$source)) {
            this["Handle"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("X" in $$source)) {
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            this["Y"] = 0;
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("ZOrder" in $$source)) {
            this["ZOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowInfo($$parsedSource as Partial<WindowInfo>);
    }
}

// Private type creation functions
const $$createType0 = CrashSessionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = CrashRecordInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = WindowInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = AppUpdateMeta.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
