package project

import (
	"fmt"
	"strings"
	"time"

	"github.com/qomos-w/gospore/actor"
	"github.com/qomos-w/sporemind/pkg/domain"
	gen "github.com/qomos-w/sporemind/pkg/domain/gen"
)

// templateIDPrefix is the namespacing separator used to remap node ids when a
// workflow map is saved as a template or instantiated. Using "::" keeps every
// produced id unique while remaining reversible — strings.SplitN(id, "::", 2)
// recovers (prefix, sourceID). The character is safe across the cardstore
// (only "/" is replaced in the fs path, ":" is round-tripped on Windows).
const templateIDPrefix = "::"

// ── template_save ──────────────────────────────────────────────────────────

// handleWikiTemplateSave snapshots a workflow map MapId into a new template
// map TemplateId. The source map's authoritative workflow_topo graph (nodes
// + depends_on edges + data-flow bindings) is copied with node ids remapped
// to template-namespaced ids; every task card is copied with runtime fields
// stripped (status, ownerAgentId, task_outputs, depends_on frontmatter
// projection) and stamped data.template:true. The template map itself carries
// data.template:true; its workflow_topo graph holds the remapped nodes/edges
// so a future template_instantiate can reconstruct a fresh instance map.
//
// Atomicity: on any failure after the first persist, the partially-created
// cards (template map + any task cards already saved) and the graph snapshot
// are rolled back in reverse order so no half-created cards remain.
func (a *Actor) handleWikiTemplateSave(ctx actor.PureContext, req domain.WikiTemplateSaveReq) (domain.WikiTemplateSaveResp, error) {
	if req.MapID == "" {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: MapId is required")
	}
	if req.TemplateID == "" {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: TemplateId is required")
	}
	if req.MapID == req.TemplateID {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: TemplateId must differ from MapId")
	}
	if strings.HasPrefix(req.TemplateID, builtinCardPrefix) {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: cannot create builtin card")
	}
	if a.externalProviderFor(req.TemplateID) != nil {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: cannot create external card")
	}
	if _, err := a.store.Get(req.TemplateID); err == nil {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: card %q already exists", req.TemplateID)
	}

	// Validate the source map.
	srcMap, err := a.store.Get(req.MapID)
	if err != nil {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: %w", err)
	}
	if srcMap.Type != "workflow" {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: card %q is type %q, not workflow", req.MapID, srcMap.Type)
	}
	if cardIsTemplate(srcMap) {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: source map %q is already a template (data.template:true)", req.MapID)
	}

	// Load the source's authoritative topology (reconciled from frontmatter on
	// first access; handles legacy maps without a snapshot).
	srcGraph := a.reconcileWorkflowTopo(req.MapID)
	if len(srcGraph.Nodes) == 0 {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: source map %q has no task cards to snapshot", req.MapID)
	}

	// Build the id mapping. Template task ids are namespaced as
	// "<TemplateId>::<sourceTaskId>" so they are globally unique even when
	// multiple maps share task names, and the mapping is trivially reversible
	// by the caller.
	idMap := make(map[string]string, len(srcGraph.Nodes))
	orderedSourceIDs := make([]string, 0, len(srcGraph.Nodes))
	for _, n := range srcGraph.Nodes {
		newID := templateTaskID(req.TemplateID, n.ID)
		idMap[n.ID] = newID
		orderedSourceIDs = append(orderedSourceIDs, n.ID)
	}

	// Build the remapped graph early so we can project edges to task-card
	// frontmatter during the copy loop.
	remapped := remapGraph(srcGraph, idMap)

	// Conflict check: ensure no remapped id collides with an existing card.
	for _, newID := range idMap {
		if _, err := a.store.Get(newID); err == nil {
			return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: would overwrite existing card %q", newID)
		}
	}

	// Construct the template map card body.
	now := time.Now().UTC().Format(time.RFC3339)
	includeIDs := make([]string, 0, len(idMap))
	for _, srcID := range orderedSourceIDs {
		includeIDs = append(includeIDs, idMap[srcID])
	}
	mapBody := "# " + req.TemplateID + "\n\n**Template of:** " + req.MapID + "\n\n" +
		"This template was generated by project.wiki.template_save. The topology is stored in\n" +
		"the task-card frontmatter (depends_on); bindings and map-level inputs are in the\n" +
		"workflow_topo card data. Use project.wiki.template_instantiate to spawn a runnable instance.\n\n" +
		"## Not yet specified\n\n_(intake questions, declared as data.inputs on task cards)_\n\n" +
		"## Decisions-so-far\n\n_(empty — populated by template_instantiate)_\n"

	mapRaw := "---\nid: " + req.TemplateID + "\ntype: workflow\ntags: []\nstatus: doing\n" +
		"created: " + quoteValue(now) + "\nmodified: " + quoteValue(now) + "\n" +
		"data:\n  template: true\n  source_map: " + req.MapID + "\n  scope:\n    include: []\n---\n\n" + mapBody

	if err := validateCard(req.TemplateID, mapRaw); err != nil {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: %w", err)
	}

	// Rollback bookkeeping: track every card we create so a mid-flight failure
	// can be cleaned up. Order is "map first, then tasks in idMap order"; on
	// rollback we delete in reverse.
	rollback := make([]string, 0, len(idMap)+1)
	rollback = append(rollback, req.TemplateID)
	rollbackOK := func() {
		for i := len(rollback) - 1; i >= 0; i-- {
			_ = a.store.Delete(rollback[i])
		}
	}

	if err := a.store.Save(&CardRecord{Title: req.TemplateID, Raw: mapRaw}); err != nil {
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: save template map: %w", err)
	}

	// Initialize the template map's workflow_topo graph (empty envelope) so
	// that any reconcile-on-read path treats it as a real, persisted graph
	// rather than a missing snapshot. We replace it with the full remapped
	// graph in one save below.
	if err := a.saveWorkflowTopo(ctx, req.TemplateID, WorkflowTopoGraph{
		Nodes: []WorkflowTopoNode{},
		Edges: []WorkflowTopoEdge{},
	}, ""); err != nil {
		rollbackOK()
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: init graph: %w", err)
	}

	// Copy each task card with runtime fields stripped.
	for _, srcID := range orderedSourceIDs {
		newID := idMap[srcID]
		srcTask, err := a.store.Get(srcID)
		if err != nil {
			rollbackOK()
			return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: read source task %q: %w", srcID, err)
		}
		taskRaw := buildTemplateTaskRaw(newID, req.TemplateID, srcTask.Body, now)
		if err := validateCard(newID, taskRaw); err != nil {
			rollbackOK()
			return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: %w", err)
		}
		if err := a.store.Save(&CardRecord{Title: newID, Raw: taskRaw}); err != nil {
			rollbackOK()
			return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: save template task %q: %w", newID, err)
		}
		rollback = append(rollback, newID)
	}

	// Project the remapped edges to each template task card's frontmatter
	// depends_on so the graph is derivable from cards (stateless workflow_topo).
	for _, n := range remapped.Nodes {
		if err := a.projectTopoToFrontmatter(n.ID, remapped); err != nil {
			rollbackOK()
			return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: project edges for %q: %w", n.ID, err)
		}
	}

	// Stamp the include list on the template map's data block.
	tplMapSaved, _ := a.store.Get(req.TemplateID)
	tplMapSaved.Raw = setIncludeListInDataBlock(tplMapSaved.Raw, includeIDs)
	tplMapSaved.Raw = ensureCardMeta(req.TemplateID, tplMapSaved.Raw, now)
	if err := validateCard(req.TemplateID, tplMapSaved.Raw); err != nil {
		rollbackOK()
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: %w", err)
	}
	if err := a.store.Save(tplMapSaved); err != nil {
		rollbackOK()
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: save include list: %w", err)
	}

	// Persist non-derivable state (bindings, map-level inputs) and bump the
	// revision counter. Nodes and depends_on edges live in card frontmatter
	// and are recomputed on read.
	if err := a.saveWorkflowTopo(ctx, req.TemplateID, remapped, ""); err != nil {
		rollbackOK()
		return domain.WikiTemplateSaveResp{}, fmt.Errorf("project.wiki.template_save: save remapped graph: %w", err)
	}

	// Notify listeners.
	savedMap, _ := a.store.Get(req.TemplateID)
	a.emitCardChanged(ctx, savedMap)
	for _, newID := range idMap {
		if saved, gerr := a.store.Get(newID); gerr == nil {
			a.emitCardChanged(ctx, saved)
		}
	}

	resp := domain.WikiTemplateSaveResp{TemplateMap: cardToListItem(savedMap)}
	for _, srcID := range orderedSourceIDs {
		resp.NodeMap = append(resp.NodeMap, gen.TemplateNodeMapping{From: srcID, To: idMap[srcID]})
	}
	return resp, nil
}

// ── template_instantiate ───────────────────────────────────────────────────

// handleWikiTemplateInstantiate copies a template map TemplateMapId (must
// have data.template:true) into a new runnable instance map InstanceMapId.
// The template's workflow_topo graph is copied with node ids remapped to
// instance-namespaced ids; each template task card is copied into a fresh
// instance card stamped data.instance_of:<template task id>, status:backlog,
// with depends_on projected from the instance graph. Instance task ids carry
// the instance prefix so multiple instantiations of the same template can
// coexist.
//
// Atomicity: same rollback strategy as template_save. On any failure after
// the first persist, all created cards and the instance graph snapshot are
// removed before returning the error.
func (a *Actor) handleWikiTemplateInstantiate(ctx actor.PureContext, req domain.WikiTemplateInstantiateReq) (domain.WikiTemplateInstantiateResp, error) {
	if req.TemplateMapID == "" {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: TemplateMapId is required")
	}
	if req.InstanceMapID == "" {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: InstanceMapId is required")
	}
	if req.TemplateMapID == req.InstanceMapID {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: InstanceMapId must differ from TemplateMapId")
	}
	if strings.HasPrefix(req.InstanceMapID, builtinCardPrefix) {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: cannot create builtin card")
	}
	if a.externalProviderFor(req.InstanceMapID) != nil {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: cannot create external card")
	}
	if _, err := a.store.Get(req.InstanceMapID); err == nil {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: card %q already exists", req.InstanceMapID)
	}

	// Validate the source template.
	tplMap, err := a.store.Get(req.TemplateMapID)
	if err != nil {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: %w", err)
	}
	if tplMap.Type != "workflow" {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: card %q is type %q, not workflow", req.TemplateMapID, tplMap.Type)
	}
	if !cardIsTemplate(tplMap) {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: source %q is not a template (data.template must be true)", req.TemplateMapID)
	}

	// Channel (b): validate instantiation parameters against the template's
	// data.inputs contract (if any). A template without data.inputs declares no
	// input constraint, so any (or no) Inputs are accepted. When a contract
	// exists, every declared field must be present in req.Inputs and match its
	// type spec. Validation failure aborts the instantiation — no instance is
	// created.
	if errs := validateInputsAgainstContract(tplMap, req.Inputs); len(errs) > 0 {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: inputs validation failed: %s", errs[0].Message)
	}

	// Load the template's authoritative topology.
	tplGraph := a.reconcileWorkflowTopo(req.TemplateMapID)
	if len(tplGraph.Nodes) == 0 {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: template %q has no task cards to instantiate", req.TemplateMapID)
	}

	// Build the id mapping: instance ids are namespaced under the instance map
	// so the same template can be instantiated multiple times without id
	// collisions. Format: "<InstanceMapId>::<templateTaskId>".
	idMap := make(map[string]string, len(tplGraph.Nodes))
	orderedTemplateIDs := make([]string, 0, len(tplGraph.Nodes))
	for _, n := range tplGraph.Nodes {
		newID := templateTaskID(req.InstanceMapID, n.ID)
		idMap[n.ID] = newID
		orderedTemplateIDs = append(orderedTemplateIDs, n.ID)
	}

	// Conflict check: ensure no remapped id collides with an existing card.
	for _, newID := range idMap {
		if _, err := a.store.Get(newID); err == nil {
			return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: would overwrite existing card %q", newID)
		}
	}

	// Construct the instance map card. The instance map records its
	// provenance via data.instance_of so the lineage is preserved.
	now := time.Now().UTC().Format(time.RFC3339)
	includeIDs := make([]string, 0, len(idMap))
	for _, tplID := range orderedTemplateIDs {
		includeIDs = append(includeIDs, idMap[tplID])
	}
	mapBody := "# " + req.InstanceMapID + "\n\n**Instance of:** " + req.TemplateMapID + "\n\n" +
		"This instance was generated by project.wiki.template_instantiate. Each task card is\n" +
		"an independent copy of the template's card and carries data.instance_of pointing back\n" +
		"to its source. Edits here do not affect the template; edits to the template do not\n" +
		"affect previously instantiated copies.\n\n" +
		"## Not yet specified\n\n_(open questions, declared as data.inputs on task cards)_\n\n" +
		"## Decisions-so-far\n\n_(empty — appended as task cards resolve)_\n"

	// Data block provenance: instance_of links back to the template, and
	// scheduler_card_id (only when driven by a timer fire) links the instance
	// to the scheduler card that created it for back-tracing.
	dataBlock := "  instance_of: " + req.TemplateMapID + "\n  scope:\n    include: []\n"
	if req.SchedulerCardID != "" {
		dataBlock += "  scheduler_card_id: " + quoteValue(req.SchedulerCardID) + "\n"
	}
	mapRaw := "---\nid: " + req.InstanceMapID + "\ntype: workflow\ntags: []\nstatus: doing\n" +
		"created: " + quoteValue(now) + "\nmodified: " + quoteValue(now) + "\n" +
		"data:\n" + dataBlock + "---\n\n" + mapBody

	if err := validateCard(req.InstanceMapID, mapRaw); err != nil {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: %w", err)
	}

	// Rollback bookkeeping. The instance graph snapshot is purged on rollback
	// alongside the card deletes.
	rollback := make([]string, 0, len(idMap)+1)
	rollback = append(rollback, req.InstanceMapID)
	rollbackOK := func() {
		for i := len(rollback) - 1; i >= 0; i-- {
			_ = a.store.Delete(rollback[i])
		}
	}

	if err := a.store.Save(&CardRecord{Title: req.InstanceMapID, Raw: mapRaw}); err != nil {
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: save instance map: %w", err)
	}

	// Initialize the instance map's workflow_topo graph; replaced with the
	// full remapped graph below.
	if err := a.saveWorkflowTopo(ctx, req.InstanceMapID, WorkflowTopoGraph{
		Nodes: []WorkflowTopoNode{},
		Edges: []WorkflowTopoEdge{},
	}, ""); err != nil {
		rollbackOK()
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: init graph: %w", err)
	}

	// Copy each task card into a fresh instance card. Instance cards are
	// immediately runnable: status=backlog, parent=instance map, and the
	// data.depends_on projection is filled in below from the remapped graph.
	for _, tplID := range orderedTemplateIDs {
		newID := idMap[tplID]
		tplTask, err := a.store.Get(tplID)
		if err != nil {
			rollbackOK()
			return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: read template task %q: %w", tplID, err)
		}
		// Look up the remapped depends_on set for this task. Edges live in
		// the graph snapshot; we project them into the frontmatter so the
		// claim guard and any frontmatter-reading code see the new edges
		// without first touching the graph.
		var deps []string
		for _, e := range tplGraph.Edges {
			if e.From == tplID && e.Kind == "depends_on" {
				deps = append(deps, e.To)
			}
		}
		remappedDeps := make([]string, 0, len(deps))
		for _, d := range deps {
			if remapped, ok := idMap[d]; ok {
				remappedDeps = append(remappedDeps, remapped)
			}
		}
		taskRaw := buildInstanceTaskRaw(newID, req.InstanceMapID, tplID, tplTask.Body, remappedDeps, now)
		if err := validateCard(newID, taskRaw); err != nil {
			rollbackOK()
			return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: %w", err)
		}
		if err := a.store.Save(&CardRecord{Title: newID, Raw: taskRaw}); err != nil {
			rollbackOK()
			return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: save instance task %q: %w", newID, err)
		}
		rollback = append(rollback, newID)
	}

	// Stamp the include list on the instance map.
	instMapSaved, _ := a.store.Get(req.InstanceMapID)
	instMapSaved.Raw = setIncludeListInDataBlock(instMapSaved.Raw, includeIDs)
	instMapSaved.Raw = ensureCardMeta(req.InstanceMapID, instMapSaved.Raw, now)
	if err := validateCard(req.InstanceMapID, instMapSaved.Raw); err != nil {
		rollbackOK()
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: %w", err)
	}
	if err := a.store.Save(instMapSaved); err != nil {
		rollbackOK()
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: save include list: %w", err)
	}

	// Persist the remapped graph snapshot. The instance graph is now the
	// authoritative source of truth for the new map's topology. Channel (b):
	// the validated instantiation parameters are written into the instance
	// graph's map-level Inputs table so downstream tasks can bind to them.
	remapped := remapGraph(tplGraph, idMap)
	if len(req.Inputs) > 0 {
		topoSetMapInputs(&remapped, req.Inputs)
	}
	if err := a.saveWorkflowTopo(ctx, req.InstanceMapID, remapped, ""); err != nil {
		rollbackOK()
		return domain.WikiTemplateInstantiateResp{}, fmt.Errorf("project.wiki.template_instantiate: save remapped graph: %w", err)
	}

	// Notify listeners.
	savedMap, _ := a.store.Get(req.InstanceMapID)
	a.emitCardChanged(ctx, savedMap)
	for _, newID := range idMap {
		if saved, gerr := a.store.Get(newID); gerr == nil {
			a.emitCardChanged(ctx, saved)
		}
	}

	// Record the run in the template's run history (best-effort; failure does
	// not abort the instantiation).
	if err := a.recordTemplateRun(req.TemplateMapID, req.InstanceMapID, req.SchedulerCardID, req.Source); err != nil {
		ctx.Logger().Warn("failed to record template run", "template", req.TemplateMapID, "instance", req.InstanceMapID, "error", err)
	}

	resp := domain.WikiTemplateInstantiateResp{InstanceMap: cardToListItem(savedMap)}
	for _, tplID := range orderedTemplateIDs {
		resp.NodeMap = append(resp.NodeMap, gen.TemplateNodeMapping{From: tplID, To: idMap[tplID]})
	}
	return resp, nil
}

// ── helpers ────────────────────────────────────────────────────────────────

// templateTaskID composes a namespaced id "<prefix>::<sourceID>". The same
// helper serves both template_save (prefix = template map id) and
// template_instantiate (prefix = instance map id), so the rule is uniform:
// whatever map owns the new cards also prefixes their ids.
func templateTaskID(prefix, sourceID string) string {
	return prefix + templateIDPrefix + sourceID
}

// remapGraph returns a copy of src with every node id translated through
// idMap (and the same translation applied to every edge endpoint and binding
// endpoint). Edges or bindings whose endpoint is missing from idMap are
// dropped: a dangling reference inside the snapshot would later be reported
// by topoDanglingEdges, and silent corruption of the source ids would leak
// the prefix into the original map.
func remapGraph(src WorkflowTopoGraph, idMap map[string]string) WorkflowTopoGraph {
	nodes := make([]WorkflowTopoNode, 0, len(src.Nodes))
	for _, n := range src.Nodes {
		newID, ok := idMap[n.ID]
		if !ok {
			continue
		}
		nodes = append(nodes, WorkflowTopoNode{
			ID:     newID,
			Status: n.Status,
			Tags:   n.Tags,
		})
	}
	edges := make([]WorkflowTopoEdge, 0, len(src.Edges))
	for _, e := range src.Edges {
		from, okFrom := idMap[e.From]
		to, okTo := idMap[e.To]
		if !okFrom || !okTo {
			continue
		}
		edges = append(edges, WorkflowTopoEdge{From: from, To: to, Kind: e.Kind})
	}
	bindings := make([]WorkflowTopoBinding, 0, len(src.Bindings))
	for _, b := range src.Bindings {
		node, okNode := idMap[b.Node]
		fromNode, okFrom := idMap[b.FromNode]
		if !okNode || !okFrom {
			continue
		}
		bindings = append(bindings, WorkflowTopoBinding{
			Node:       node,
			Input:      b.Input,
			FromNode:   fromNode,
			FromOutput: b.FromOutput,
		})
	}
	return WorkflowTopoGraph{Nodes: nodes, Edges: edges, Bindings: bindings}
}

// buildTemplateTaskRaw renders a template task card's frontmatter. The
// template card carries no runtime state: status is fixed at "backlog"
// (template cards are not directly runnable, but every card needs a valid
// status), and data.template:true is stamped so the contract validator and
// downstream readers can recognize the role. depends_on is projected onto the
// card's frontmatter by the caller (projectTopoToFrontmatter) after the card is
// saved so the graph is derivable from cards. Tags include the template map
// id, the parent is the template map, matching the workflow map convention.
func buildTemplateTaskRaw(newID, templateID, body, now string) string {
	return "---\nid: " + newID + "\ntype: task\ntags: [" + templateID + "]\n" +
		"status: backlog\nparent: " + templateID + "\n" +
		"created: " + quoteValue(now) + "\nmodified: " + quoteValue(now) + "\n" +
		"data:\n  template: true\n---\n\n" + body + "\n"
}

// buildInstanceTaskRaw renders an instance task card's frontmatter. Instance
// cards are immediately runnable: status is "backlog" (the standard starting
// state for claimable work), parent is the instance map, and data.instance_of
// records the originating template task id. depends_on is projected from the
// remapped instance graph so claim-guard and frontmatter readers see the
// new edges without first reaching for the graph snapshot.
func buildInstanceTaskRaw(newID, instanceID, templateTaskID, body string, remappedDeps []string, now string) string {
	deps := yamlStringList(remappedDeps, "    ")
	return "---\nid: " + newID + "\ntype: task\ntags: [" + instanceID + "]\n" +
		"status: backlog\nparent: " + instanceID + "\n" +
		"created: " + quoteValue(now) + "\nmodified: " + quoteValue(now) + "\n" +
		"data:\n  instance_of: " + templateTaskID + "\n  depends_on: " + deps + "---\n\n" + body + "\n"
}

// setIncludeListInDataBlock writes the include list (block-style) into the
// data block of a workflow map. If a data.scope.include already exists it is
// replaced; otherwise data.scope.include is created. This is the inverse of
// appendIncludeID (which only ever appends a single id); here we are seeding a
// full list at construction time, so replacement is the right operation.
func setIncludeListInDataBlock(raw string, ids []string) string {
	if !strings.HasPrefix(raw, "---") {
		return raw
	}
	end := strings.Index(raw[3:], "---")
	if end < 0 {
		return raw
	}
	front := raw[3 : 3+end]
	lines := strings.Split(front, "\n")

	// Locate the data: block.
	dataIdx := -1
	for i, line := range lines {
		if strings.TrimSpace(line) == "data:" && (len(line) == 0 || line[0] != ' ') {
			dataIdx = i
			break
		}
	}
	// Build the YAML representation of the include list. Empty list renders as
	// "[]"; non-empty renders as a block list under data.scope.include.
	var includeBlock string
	if len(ids) == 0 {
		includeBlock = "  scope:\n    include: []"
	} else {
		var sb strings.Builder
		sb.WriteString("  scope:\n    include:")
		for _, id := range ids {
			sb.WriteString("\n      - ")
			sb.WriteString(id)
		}
		includeBlock = sb.String()
	}

	if dataIdx < 0 {
		lines = append(lines, "data:")
		lines = append(lines, strings.Split(includeBlock, "\n")...)
		return rebuildFront(lines, raw, end)
	}

	// Rebuild the data block: drop existing scope/include entries, keep the
	// other children (template:, source_map:, …), then write the fresh
	// include block first. Scanning per direct-child subtree avoids the
	// duplicate-scope-key corruption when every child of data: is indented
	// (no column-0 sentinel line before the closing ---).
	head := lines[:dataIdx+1]
	tail := lines[dataIdx+1:]
	var kept []string
	for i := 0; i < len(tail); {
		line := tail[i]
		if line != "" && line[0] != ' ' && line[0] != '\t' {
			// Column-0 line: outside the data block. Keep the remainder verbatim.
			kept = append(kept, tail[i:]...)
			break
		}
		if strings.TrimSpace(line) == "" {
			kept = append(kept, line)
			i++
			continue
		}
		indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]
		key := strings.TrimSpace(strings.SplitN(line, ":", 2)[0])
		// End of this entry's subtree: first following line at same-or-lower indent.
		j := i + 1
		for j < len(tail) {
			next := tail[j]
			if next == "" {
				break
			}
			nIndent := next[:len(next)-len(strings.TrimLeft(next, " \t"))]
			if len(nIndent) <= len(indent) {
				break
			}
			j++
		}
		if key != "scope" && key != "include" {
			kept = append(kept, tail[i:j]...)
		}
		i = j
	}
	lines = append(head, strings.Split(includeBlock, "\n")...)
	lines = append(lines, kept...)
	return rebuildFront(lines, raw, end)
}
