package appmanager

import (
	"strings"
	"testing"

	"github.com/qomos-w/sporemind/pkg/appdef"
	"github.com/qomos-w/sporemind/pkg/codegen"
	gen "github.com/qomos-w/sporemind/pkg/domain/gen"
)

const testAppDef = `// test.appdef
app TestApp {
    id:          "app.test"
    name:        "TestApp"
    version:     "1.0.0"
    namespace:   "test"
    permissions: ["fs.read"]

    struct GreetRequest {
        Name: string
    }

    callable greet {
        request:  GreetRequest
        response: string
        effect:   "read"
        service:  "appmanager"
    }

    callable farewell {
        effect: "read"
        service: "appmanager"
    }
}
`

func TestCheckBuildGate(t *testing.T) {
	t.Run("pass", func(t *testing.T) {
		res := checkBuildGate(gen.NativeBuildResult{Success: true, ArtifactPath: "/tmp/plugin.so"})
		if !res.Passed || res.Error != nil {
			t.Fatalf("expected build gate to pass, got %+v", res)
		}
	})
	t.Run("fail with diagnostic", func(t *testing.T) {
		res := checkBuildGate(gen.NativeBuildResult{Success: false, Diagnostic: "undefined: foo"})
		if res.Passed {
			t.Fatal("expected build gate to fail")
		}
		if !strings.Contains(res.Error.Detail, "undefined: foo") {
			t.Fatalf("expected diagnostic in error detail, got %q", res.Error.Detail)
		}
		if res.Error.Gate != GateBuild {
			t.Fatalf("expected gate %q, got %q", GateBuild, res.Error.Gate)
		}
	})
}

func TestCheckStubFillingGate(t *testing.T) {
	t.Run("pass", func(t *testing.T) {
		res := checkStubFillingGate(map[string]string{
			"handlers.go": "func greet() error { return nil }",
		})
		if !res.Passed {
			t.Fatalf("expected stub gate to pass, got %+v", res)
		}
	})
	t.Run("fail", func(t *testing.T) {
		res := checkStubFillingGate(map[string]string{
			"handlers.go": "func greet() error { return sdk.ErrNotImplemented }\nfunc farewell() error { return sdk.ErrNotImplemented }",
			"main.go":     "package main",
		})
		if res.Passed {
			t.Fatal("expected stub gate to fail")
		}
		if !strings.Contains(res.Error.Detail, "handlers.go") {
			t.Fatalf("expected handlers.go in detail, got %q", res.Error.Detail)
		}
		if strings.Contains(res.Error.Detail, "main.go") {
			t.Fatalf("main.go should not be flagged, got %q", res.Error.Detail)
		}
	})
}

func TestCheckManifestGate(t *testing.T) {
	manifest := manifestFromAppDef(t, testAppDef)
	hash := hashString(testAppDef)

	t.Run("pass", func(t *testing.T) {
		res := checkManifestGate(testAppDef, hash, manifest, &codegen.GeneratedManifest{AppDefHash: hash})
		if !res.Passed {
			t.Fatalf("expected manifest gate to pass, got %+v", res)
		}
	})

	t.Run("fail drift", func(t *testing.T) {
		res := checkManifestGate(testAppDef, hash, manifest, &codegen.GeneratedManifest{AppDefHash: "oldhash"})
		if res.Passed {
			t.Fatal("expected manifest gate to fail on drift")
		}
		if !strings.Contains(res.Error.Detail, "changed since last dev_generate") {
			t.Fatalf("expected drift message, got %q", res.Error.Detail)
		}
	})

	t.Run("fail manifest mismatch", func(t *testing.T) {
		badManifest := manifest
		badManifest.Version = "2.0.0"
		res := checkManifestGate(testAppDef, hash, badManifest, nil)
		if res.Passed {
			t.Fatal("expected manifest gate to fail on mismatch")
		}
		if !strings.Contains(res.Error.Detail, "Version") {
			t.Fatalf("expected Version mismatch in detail, got %q", res.Error.Detail)
		}
	})

	t.Run("fail missing callable", func(t *testing.T) {
		badManifest := manifest
		badManifest.Callables = badManifest.Callables[:1]
		res := checkManifestGate(testAppDef, hash, badManifest, nil)
		if res.Passed {
			t.Fatal("expected manifest gate to fail on missing callable")
		}
		if !strings.Contains(res.Error.Detail, "farewell") {
			t.Fatalf("expected farewell missing in detail, got %q", res.Error.Detail)
		}
	})
}

// TestCheckManifestGateExposeWatch verifies the manifest-consistency gate
// flags drift on the callable expose and watch fields, so a manifest edited
// out from under the .appdef (or generated by a stale dev_generate) is caught
// with a field-specific message.
func TestCheckManifestGateExposeWatch(t *testing.T) {
	const src = `app Surfaces {
    id:          "app.surfaces"
    name:        "Surfaces"
    version:     "0.1.0"
    namespace:   "surfaces"

    struct Ping {
        ok: bool
    }

    event item_changed {
        payload: Ping
    }

    callable panel_only {
        request:  Ping
        response: Ping
        expose:   "frontend"
        watch:    ["item_changed"]
    }
}`
	manifest := manifestFromAppDef(t, src)
	hash := hashString(src)

	t.Run("pass when matching", func(t *testing.T) {
		res := checkManifestGate(src, hash, manifest, nil)
		if !res.Passed {
			t.Fatalf("expected manifest gate to pass, got %+v", res)
		}
	})

	t.Run("fail on expose drift", func(t *testing.T) {
		bad := manifest
		bad.Callables = append([]gen.AppCallableDescriptor(nil), manifest.Callables...)
		bad.Callables[0].Expose = "agent"
		res := checkManifestGate(src, hash, bad, nil)
		if res.Passed {
			t.Fatal("expected manifest gate to fail on expose drift")
		}
		if !strings.Contains(res.Error.Detail, `Expose`) {
			t.Fatalf("expected Expose mismatch in detail, got %q", res.Error.Detail)
		}
	})

	t.Run("fail on watch drift", func(t *testing.T) {
		bad := manifest
		bad.Callables = append([]gen.AppCallableDescriptor(nil), manifest.Callables...)
		bad.Callables[0].Watch = nil
		res := checkManifestGate(src, hash, bad, nil)
		if res.Passed {
			t.Fatal("expected manifest gate to fail on watch drift")
		}
		if !strings.Contains(res.Error.Detail, "Watch") {
			t.Fatalf("expected Watch mismatch in detail, got %q", res.Error.Detail)
		}
	})
}

func TestCheckCoverageGate(t *testing.T) {
	manifest := manifestFromAppDef(t, testAppDef)

	t.Run("pass with namespaced ids", func(t *testing.T) {
		res := checkCoverageGate(manifest, []string{
			"plugin.app.test.greet",
			"plugin.app.test.farewell",
		}, "")
		if !res.Passed {
			t.Fatalf("expected coverage gate to pass, got %+v", res)
		}
	})

	t.Run("pass with local ids", func(t *testing.T) {
		res := checkCoverageGate(manifest, []string{"greet", "farewell"}, "")
		if !res.Passed {
			t.Fatalf("expected coverage gate to pass with local ids, got %+v", res)
		}
	})

	t.Run("fail missing callable", func(t *testing.T) {
		res := checkCoverageGate(manifest, []string{"plugin.app.test.greet"}, "")
		if res.Passed {
			t.Fatal("expected coverage gate to fail")
		}
		if !strings.Contains(res.Error.Detail, "farewell") {
			t.Fatalf("expected farewell in detail, got %q", res.Error.Detail)
		}
	})

	t.Run("load diagnostic surfaces as root cause", func(t *testing.T) {
		res := checkCoverageGate(manifest, nil, "pluginhost: process opener: plugin \"app.test\" already spawned")
		if res.Passed {
			t.Fatal("expected coverage gate to fail")
		}
		if !strings.Contains(res.Error.Detail, "already spawned") {
			t.Fatalf("expected load diagnostic in detail, got %q", res.Error.Detail)
		}
		if strings.Contains(res.Error.Detail, "not registered in dispatch registry") {
			t.Fatalf("misleading registry diff should be suppressed, got %q", res.Error.Detail)
		}
	})
}

// TestCheckVendorGate pins the vendor_freshness policy: only a confirmed
// stamp/digest mismatch fails; not-vendored, legacy unstamped trees, and an
// unavailable host digest all pass.
func TestCheckVendorGate(t *testing.T) {
	cases := []struct {
		name   string
		stamp  string
		digest string
		pass   bool
	}{
		{"not vendored", "", "abc", true},
		{"legacy unstamped tree", "", "", true},
		{"digest unavailable", "abc", "", true},
		{"fresh", "abc", "abc", true},
		{"stale", "abc", "def", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res := checkVendorGate(tc.stamp, tc.digest)
			if res.Passed != tc.pass {
				t.Fatalf("checkVendorGate(%q,%q) passed=%v, want %v (err=%+v)", tc.stamp, tc.digest, res.Passed, tc.pass, res.Error)
			}
			if !tc.pass && res.Error == nil {
				t.Fatal("failing gate must carry a structured error")
			}
		})
	}
}

// TestRunAllGatesIncludesVendorGate wires the new gate into the full report:
// a stale vendored SDK fails the whole report with a fix hint pointing at
// appmanager.sdk_vendor.
func TestRunAllGatesIncludesVendorGate(t *testing.T) {
	manifest := manifestFromAppDef(t, testAppDef)
	hash := hashString(testAppDef)
	report := RunAllGates(GateDeps{
		SourceFiles:         map[string]string{"handlers.go": "func greet() {}"},
		AppDefContent:       testAppDef,
		AppDefHash:          hash,
		Manifest:            manifest,
		GeneratedManifest:   &codegen.GeneratedManifest{AppDefHash: hash},
		BuildResult:         gen.NativeBuildResult{Success: true},
		RegisteredCallables: []string{"greet", "farewell"},
		VendorStamp:         "old-digest",
		HostSDKDigest:       "new-digest",
	})
	if report.Passed {
		t.Fatal("expected report to fail on stale vendor-sdk")
	}
	var vendor *GateResult
	for i, r := range report.Results {
		if r.Gate == GateVendor {
			vendor = &report.Results[i]
		}
	}
	if vendor == nil {
		t.Fatalf("vendor_freshness gate missing from results: %+v", report.Results)
	}
	if vendor.Passed || vendor.Error == nil || !strings.Contains(vendor.Error.Fix, "appmanager.sdk_vendor") {
		t.Fatalf("vendor gate = %+v, want failure with sdk_vendor fix hint", vendor)
	}
}

func TestRunAllGates(t *testing.T) {
	manifest := manifestFromAppDef(t, testAppDef)
	hash := hashString(testAppDef)

	t.Run("all pass", func(t *testing.T) {
		report := RunAllGates(GateDeps{
			SourceFiles:         map[string]string{"handlers.go": "func greet() {}"},
			AppDefContent:       testAppDef,
			AppDefHash:          hash,
			Manifest:            manifest,
			GeneratedManifest:   &codegen.GeneratedManifest{AppDefHash: hash},
			BuildResult:         gen.NativeBuildResult{Success: true},
			RegisteredCallables: []string{"greet", "farewell"},
		})
		if !report.Passed {
			t.Fatalf("expected all gates to pass, got %+v", report)
		}
	})

	t.Run("stub gate fails with build injected", func(t *testing.T) {
		report := RunAllGates(GateDeps{
			SourceFiles:         map[string]string{"handlers.go": "func greet() error { return sdk.ErrNotImplemented }"},
			AppDefContent:       testAppDef,
			AppDefHash:          hash,
			Manifest:            manifest,
			GeneratedManifest:   &codegen.GeneratedManifest{AppDefHash: hash},
			BuildResult:         gen.NativeBuildResult{Success: true},
			RegisteredCallables: []string{"greet", "farewell"},
		})
		if report.Passed {
			t.Fatal("expected report to fail")
		}
		found := false
		for _, r := range report.Results {
			if r.Gate == GateStubFill && !r.Passed {
				found = true
			}
		}
		if !found {
			t.Fatalf("expected stub_filling gate failure, got %+v", report)
		}
	})

	t.Run("build gate fails with fake result", func(t *testing.T) {
		report := RunAllGates(GateDeps{
			SourceFiles:         map[string]string{"handlers.go": "func greet() {}"},
			AppDefContent:       testAppDef,
			AppDefHash:          hash,
			Manifest:            manifest,
			GeneratedManifest:   &codegen.GeneratedManifest{AppDefHash: hash},
			BuildResult:         gen.NativeBuildResult{Success: false, Diagnostic: "injected build failure"},
			RegisteredCallables: []string{"greet", "farewell"},
		})
		if report.Passed {
			t.Fatal("expected report to fail")
		}
		found := false
		for _, r := range report.Results {
			if r.Gate == GateBuild && !r.Passed && strings.Contains(r.Error.Detail, "injected build failure") {
				found = true
			}
		}
		if !found {
			t.Fatalf("expected build gate failure with injected diagnostic, got %+v", report)
		}
	})
}

func manifestFromAppDef(t *testing.T, src string) gen.AppManifest {
	t.Helper()
	app, diags, err := appdef.ParseFile(src)
	if err != nil {
		t.Fatalf("parse appdef: %v", err)
	}
	if len(diags) > 0 {
		t.Fatalf("appdef diagnostics: %v", diags)
	}
	m, err := codegen.GenerateManifestFromAppDef(app)
	if err != nil {
		t.Fatalf("generate manifest: %v", err)
	}
	return m
}

// TestCheckFrontendGate pins the frontend_transport policy: no HTML passes
// (nothing to lint), the direct-HTTP path passes, and dead pre-T5 bridge
// tokens fail with the migration fix hint.
func TestCheckFrontendGate(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		pass  bool
	}{
		{"no html", nil, true},
		{"direct http path", map[string]string{"index.html": "<script>const b=window.__sporemindAppBase;fetch(b+'/invoke/t');EventSource(b+'/events')</script>"}, true},
		{"legacy api route", map[string]string{"index.html": "fetch('/api/pluginhost.invoke',{method:'POST'})"}, false},
		{"legacy window handle", map[string]string{"panel.html": "window.sporemind.invoke('x')"}, false},
		{"legacy sporemind invoke token", map[string]string{"index.html": "sporemind.invoke('x')"}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res := checkFrontendGate(tc.files)
			if res.Passed != tc.pass {
				t.Fatalf("checkFrontendGate(%v) passed=%v, want %v (err=%+v)", tc.name, res.Passed, tc.pass, res.Error)
			}
			if !tc.pass && res.Error == nil {
				t.Fatal("failing gate must carry a structured error")
			}
		})
	}
}

// TestRunAllGatesIncludesFrontendGate keeps the new gate in the report order.
func TestRunAllGatesIncludesFrontendGate(t *testing.T) {
	report := RunAllGates(GateDeps{})
	found := false
	for _, r := range report.Results {
		if r.Gate == GateFrontend {
			found = true
		}
	}
	if !found {
		t.Fatalf("frontend_transport gate missing from report: %+v", report.Results)
	}
}
