import { describe, expect, it, vi, beforeEach } from 'vitest'
import type { TutorialSpec } from '../gen-types/interfacemanager'
import {
  TUTORIAL_CATEGORIES,
  dynamicTutorialStore,
  listTutorials,
  normalizeTutorialSpec,
  useDynamicTutorials,
} from './tutorial-registry'
import type { TFunction } from './onboarding-guide'

// Static categories build their steps through i18n; for store tests a
// pass-through t resolves the key itself, keeping assertions deterministic.
const t: TFunction = (key) => key

const ctx = { hasProjects: true, hasAgents: false, hasApps: false }

function spec(overrides: Partial<TutorialSpec> = {}): TutorialSpec {
  return {
    TutorialId: 'agent-how-to-search',
    Title: 'How to search',
    Description: 'Generated by an agent',
    Steps: [
      { TargetGuideId: 'composer', Title: 'Step one', Body: 'Click here' },
      { TargetGuideId: 'sidebar', Title: 'Step two', Body: 'Then here', Placement: 'right' },
    ],
    CreatedAt: '2026-09-07T00:00:00Z',
    ...overrides,
  }
}

describe('dynamicTutorialStore', () => {
  beforeEach(() => {
    dynamicTutorialStore.clear()
  })

  it('upsert inserts a new tutorial retrievable via get/getAll', () => {
    dynamicTutorialStore.upsert(spec())
    expect(dynamicTutorialStore.get('agent-how-to-search')?.Title).toBe('How to search')
    expect(dynamicTutorialStore.getAll()).toHaveLength(1)
    expect(dynamicTutorialStore.getAll()[0]?.Steps).toHaveLength(2)
  })

  it('upsert overwrites an existing tutorial with the same TutorialId', () => {
    dynamicTutorialStore.upsert(spec())
    dynamicTutorialStore.upsert(spec({ Title: 'Rewritten title', Description: undefined }))
    const all = dynamicTutorialStore.getAll()
    expect(all).toHaveLength(1)
    expect(all[0]?.Title).toBe('Rewritten title')
    expect(dynamicTutorialStore.get('agent-how-to-search')?.Description).toBeUndefined()
  })

  it('upsert ignores entries without a TutorialId', () => {
    dynamicTutorialStore.upsert(spec({ TutorialId: '' }))
    expect(dynamicTutorialStore.getAll()).toHaveLength(0)
  })

  it('upsert is a no-op when the content is unchanged', () => {
    const listener = vi.fn()
    dynamicTutorialStore.upsert(spec())
    dynamicTutorialStore.subscribe(listener)
    dynamicTutorialStore.upsert(spec())
    expect(listener).not.toHaveBeenCalled()
  })

  it('remove deletes the tutorial and notifies', () => {
    const listener = vi.fn()
    dynamicTutorialStore.upsert(spec())
    dynamicTutorialStore.subscribe(listener)
    dynamicTutorialStore.remove('agent-how-to-search')
    expect(dynamicTutorialStore.getAll()).toHaveLength(0)
    expect(listener).toHaveBeenCalledTimes(1)
  })

  it('remove of an unknown id does not notify', () => {
    const listener = vi.fn()
    dynamicTutorialStore.subscribe(listener)
    dynamicTutorialStore.remove('nope')
    expect(listener).not.toHaveBeenCalled()
  })

  it('subscribe notifies on upsert and returns an unsubscribe that stops notifications', () => {
    const listener = vi.fn()
    const unsubscribe = dynamicTutorialStore.subscribe(listener)
    dynamicTutorialStore.upsert(spec())
    expect(listener).toHaveBeenCalledTimes(1)
    unsubscribe()
    dynamicTutorialStore.upsert(spec({ TutorialId: 'another' }))
    expect(listener).toHaveBeenCalledTimes(1)
  })
})

describe('normalizeTutorialSpec', () => {
  it('tolerates camelCase input and defaults missing fields', () => {
    const normalized = normalizeTutorialSpec({ tutorialId: 'x', title: 'X', steps: null })
    expect(normalized).toEqual({
      TutorialId: 'x',
      Title: 'X',
      Description: undefined,
      Steps: [],
      CreatedAt: '',
    })
  })
})

describe('listTutorials', () => {
  beforeEach(() => {
    dynamicTutorialStore.clear()
  })

  it('returns every static category when no dynamic tutorials exist', () => {
    const items = listTutorials(t, ctx)
    expect(items.map((i) => i.id)).toEqual(TUTORIAL_CATEGORIES.map((c) => c.id))
    expect(items.every((i) => !i.isDynamic)).toBe(true)
    for (const item of items) {
      expect(item.title).toBeTruthy()
      expect(Array.isArray(item.steps)).toBe(true)
    }
  })

  it('static availability filters do not drop entries (workflow stays listed without projects)', () => {
    const items = listTutorials(t, { ...ctx, hasProjects: false })
    expect(items.map((i) => i.id)).toContain('workflow')
  })

  it('merges dynamic tutorials after static ones with normalized fields and isDynamic=true', () => {
    dynamicTutorialStore.upsert(spec())
    const items = listTutorials(t, ctx)
    expect(items).toHaveLength(TUTORIAL_CATEGORIES.length + 1)
    const dynamic = items[items.length - 1]!
    expect(dynamic.isDynamic).toBe(true)
    expect(dynamic.id).toBe('agent-how-to-search')
    expect(dynamic.title).toBe('How to search')
    expect(dynamic.description).toBe('Generated by an agent')
    expect(dynamic.steps).toHaveLength(2)
    expect(dynamic.createdAt).toBe('2026-09-07T00:00:00Z')
  })

  it('dynamic updates do not mutate the static registry', () => {
    const before = TUTORIAL_CATEGORIES.map((c) => c.id)
    dynamicTutorialStore.upsert(spec())
    dynamicTutorialStore.remove('agent-how-to-search')
    expect(TUTORIAL_CATEGORIES.map((c) => c.id)).toEqual(before)
    expect(listTutorials(t, ctx).every((i) => !i.isDynamic)).toBe(true)
  })

  it('dynamic tutorial with a reserved-word id does not shadow the static category', () => {
    dynamicTutorialStore.upsert(spec({ TutorialId: 'basics', Title: 'Shadow attempt' }))
    const items = listTutorials(t, ctx)
    const basics = items.filter((i) => i.id === 'basics')
    expect(basics).toHaveLength(2)
    expect(basics.find((i) => i.isDynamic)?.title).toBe('Shadow attempt')
    expect(basics.find((i) => !i.isDynamic)?.title).toBe('onboarding.tutorial.category.basics.label')
  })
})

describe('useDynamicTutorials', () => {
  beforeEach(() => {
    dynamicTutorialStore.clear()
  })

  it('subscribes via useSyncExternalStore (renderHook lifecycle)', async () => {
    const { renderHook, act } = await import('@testing-library/react')
    const { result, unmount } = renderHook(() => useDynamicTutorials())
    expect(result.current).toEqual([])
    act(() => {
      dynamicTutorialStore.upsert(spec())
    })
    expect(result.current).toHaveLength(1)
    expect(result.current[0]?.TutorialId).toBe('agent-how-to-search')
    act(() => {
      dynamicTutorialStore.remove('agent-how-to-search')
    })
    expect(result.current).toEqual([])
    unmount()
    // After unmount, store mutations must not leak into the unmounted hook.
    dynamicTutorialStore.upsert(spec())
  })
})
