// Card icon catalog — the authoritative name/label/keywords/category data for
// every icon the card/bundle UI can render. cardIconLibrary.tsx zips this
// catalog with lucide components in the same order; the backend embeds the
// generated copy (pkg/actor/appmanager/icon_catalog.gen.json) to serve
// appmanager.icon_names. Keep this file JSX-free so Node can import it for
// codegen (web/scripts/gen-icon-catalog.ts).

export type CardIconCategory = 'task' | 'content' | 'development' | 'collaboration' | 'status' | 'media' | 'system'

export type CardIconCatalogTuple = [name: string, label: string, keywords: string[], category: CardIconCategory]

export const CARD_ICON_CATALOG: CardIconCatalogTuple[] = [
  // Task
  ['target', 'Target', ['goal', 'objective', 'aim'], 'task'],
  ['check-circle', 'Check circle', ['done', 'complete', 'ok'], 'task'],
  ['check-square', 'Check square', ['todo', 'checkbox', 'task'], 'task'],
  ['calendar', 'Calendar', ['date', 'schedule', 'plan'], 'task'],
  ['clock', 'Clock', ['time', 'timer', 'history'], 'task'],
  ['star', 'Star', ['favorite', 'important', 'bookmark'], 'task'],
  ['flag', 'Flag', ['milestone', 'mark'], 'task'],
  ['pin', 'Pin', ['top', 'sticky', 'fix'], 'task'],
  ['bookmark', 'Bookmark', ['save', 'collection'], 'task'],
  ['circle', 'Circle', ['radio', 'empty'], 'task'],
  ['circle-dot', 'Circle dot', ['radio', 'checked'], 'task'],
  ['square-asterisk', 'Square asterisk', ['priority', 'blocker'], 'task'],
  ['trophy', 'Trophy', ['achievement', 'win'], 'task'],
  ['timer', 'Timer', ['pomodoro', 'focus'], 'task'],
  // Status
  ['zap', 'Zap', ['fast', 'energy', 'quick'], 'status'],
  ['alert-circle', 'Alert', ['warning', 'attention', 'error'], 'status'],
  ['flame', 'Flame', ['hot', 'trending', 'urgent'], 'status'],
  ['rocket', 'Rocket', ['launch', 'release', 'start'], 'status'],
  ['lightbulb', 'Idea', ['insight', 'think', 'tip'], 'status'],
  ['help-circle', 'Help', ['question', 'support'], 'status'],
  ['info', 'Info', ['notice', 'details'], 'status'],
  ['bell', 'Bell', ['notification', 'remind'], 'status'],
  ['shield-alert', 'Shield alert', ['risk', 'warning'], 'status'],
  ['shield-check', 'Shield check', ['safe', 'verified'], 'status'],
  ['siren', 'Siren', ['critical', 'incident'], 'status'],
  // Content
  ['book-open', 'Book', ['knowledge', 'read', 'wiki'], 'content'],
  ['file-text', 'Document', ['file', 'note', 'doc'], 'content'],
  ['folder', 'Folder', ['directory', 'group'], 'content'],
  ['folder-open', 'Folder open', ['open'], 'content'],
  ['folder-kanban', 'Kanban folder', ['board', 'project'], 'content'],
  ['folder-git', 'Git folder', ['repo', 'repository'], 'content'],
  ['archive', 'Archive', ['storage', 'done'], 'content'],
  ['pencil', 'Pencil', ['edit', 'write', 'draft'], 'content'],
  ['edit-3', 'Edit', ['compose', 'modify'], 'content'],
  ['notebook-pen', 'Notes', ['journal', 'log'], 'content'],
  ['newspaper', 'Article', ['news', 'blog'], 'content'],
  ['files', 'Files', ['copy', 'duplicate'], 'content'],
  ['file-plus', 'New file', ['create', 'add'], 'content'],
  ['file-minus', 'Remove file', ['delete'], 'content'],
  ['file-search', 'Search file', ['find', 'explore'], 'content'],
  ['file-code', 'Code file', ['source', 'script'], 'content'],
  ['file-json', 'JSON file', ['config', 'json'], 'content'],
  ['file-key', 'Key file', ['secret', 'pem'], 'content'],
  ['file-lock', 'Locked file', ['secure'], 'content'],
  ['file-question', 'Unknown file', ['missing'], 'content'],
  ['file-x', 'Deleted file', ['error'], 'content'],
  ['file-archive', 'Archive file', ['zip', 'compress'], 'content'],
  ['file-box', 'Package file', ['bundle'], 'content'],
  ['file-image', 'Image file', ['picture', 'photo'], 'content'],
  ['file-audio', 'Audio file', ['sound', 'music'], 'content'],
  ['file-video', 'Video file', ['movie'], 'content'],
  // Development
  ['code', 'Code', ['programming', 'develop', 'source'], 'development'],
  ['database', 'Database', ['data', 'storage', 'sql'], 'development'],
  ['bug', 'Bug', ['issue', 'error', 'fix'], 'development'],
  ['spider', 'Spider', ['crawl', 'web', 'crawler'], 'development'],
  ['terminal', 'Terminal', ['shell', 'command', 'cli'], 'development'],
  ['git-branch', 'Git branch', ['version', 'source'], 'development'],
  ['git-commit', 'Git commit', ['commit'], 'development'],
  ['git-merge', 'Git merge', ['merge'], 'development'],
  ['git-pull-request', 'Pull request', ['pr', 'review'], 'development'],
  ['cpu', 'CPU', ['compute', 'hardware'], 'development'],
  ['hard-drive', 'Hard drive', ['disk', 'storage'], 'development'],
  ['server', 'Server', ['backend', 'host'], 'development'],
  ['cloud', 'Cloud', ['deploy', 'cloud'], 'development'],
  ['binary', 'Binary', ['bits', 'hex'], 'development'],
  ['variable', 'Variable', ['var', 'state'], 'development'],
  ['layers', 'Layers', ['stack', 'module'], 'development'],
  ['puzzle', 'Puzzle', ['plugin', 'extension'], 'development'],
  ['wrench', 'Wrench', ['tool', 'config'], 'development'],
  ['plug', 'Plug', ['connect', 'adapter'], 'development'],
  ['network', 'Network', ['graph', 'nodes', 'topology', 'semantic'], 'development'],
  ['waypoints', 'Waypoints', ['route', 'path', 'orchestration', 'map'], 'development'],
  // Collaboration
  ['users', 'Users', ['team', 'people', 'group'], 'collaboration'],
  ['user', 'User', ['person', 'account'], 'collaboration'],
  ['user-plus', 'Add user', ['invite'], 'collaboration'],
  ['user-check', 'Verified user', ['approved'], 'collaboration'],
  ['corner-up-left', 'Parent', ['parent', 'up', 'back', 'ancestor'], 'collaboration'],
  ['message-circle', 'Message', ['chat', 'conversation'], 'collaboration'],
  ['message-square', 'Message square', ['comment'], 'collaboration'],
  ['mail', 'Mail', ['email', 'letter'], 'collaboration'],
  ['send', 'Send', ['share', 'forward'], 'collaboration'],
  ['link', 'Link', ['reference', 'url', 'connection'], 'collaboration'],
  ['link-2', 'Link alt', ['attach'], 'collaboration'],
  ['share-2', 'Share', ['publish'], 'collaboration'],
  ['phone', 'Phone', ['call'], 'collaboration'],
  ['phone-forwarded', 'Phone forwarded', ['call', 'relay', 'bridge'], 'collaboration'],
  ['video', 'Video', ['meeting', 'camera'], 'collaboration'],
  ['graduation-cap', 'Graduation cap', ['learn', 'teach', 'tutorial', 'education'], 'collaboration'],
  // System
  ['settings', 'Settings', ['configure', 'preferences', 'gear'], 'system'],
  ['search', 'Search', ['find', 'lookup'], 'system'],
  ['lock', 'Lock', ['private', 'security'], 'system'],
  ['unlock', 'Unlock', ['public'], 'system'],
  ['shield', 'Shield', ['safe', 'protect'], 'system'],
  ['globe', 'Globe', ['web', 'world', 'internet'], 'system'],
  ['package', 'Package', ['component', 'module', 'bundle'], 'system'],
  ['palette', 'Palette', ['design', 'color'], 'system'],
  ['home', 'Home', ['start', 'dashboard'], 'system'],
  ['layout-grid', 'Grid', ['apps', 'menu'], 'system'],
  ['layout-dashboard', 'Dashboard', ['workbench', 'board', 'overview'], 'system'],
  ['grid-3x3', 'Grid 3x3', ['matrix'], 'system'],
  ['menu', 'Menu', ['list', 'burger'], 'system'],
  ['more-horizontal', 'More', ['ellipsis'], 'system'],
  ['filter', 'Filter', ['sort'], 'system'],
  ['refresh-cw', 'Refresh', ['sync', 'reload'], 'system'],
  ['rotate-ccw', 'Undo', ['revert'], 'system'],
  ['history', 'History', ['log', 'timeline'], 'system'],
  ['trash-2', 'Trash', ['delete', 'remove'], 'system'],
  ['save', 'Save', ['persist', 'write'], 'system'],
  ['download', 'Download', ['export'], 'system'],
  ['upload', 'Upload', ['import'], 'system'],
  ['copy', 'Copy', ['duplicate'], 'system'],
  ['scissors', 'Cut', ['scissor'], 'system'],
  ['paperclip', 'Paperclip', ['attachment'], 'system'],
  ['tag', 'Tag', ['label'], 'system'],
  ['tags', 'Tags', ['labels'], 'system'],
  ['hash', 'Hash', ['number'], 'system'],
  ['bar-chart-3', 'Chart', ['graph', 'analytics'], 'system'],
  ['wifi', 'WiFi', ['network', 'wireless'], 'system'],
  ['sun', 'Sun', ['light', 'day'], 'system'],
  ['moon', 'Moon', ['dark', 'night'], 'system'],
  ['eye', 'Eye', ['view', 'visible'], 'system'],
  ['scan', 'Scan', ['qr', 'code'], 'system'],
  ['qr-code', 'QR code', ['link'], 'system'],
  ['key', 'Key', ['password', 'secret'], 'system'],
  ['crown', 'Crown', ['vip', 'owner'], 'system'],
  ['sparkles', 'Sparkles', ['magic', 'ai'], 'system'],
  ['wand-2', 'Wand', ['transform', 'magic'], 'system'],
  ['webhook', 'Webhook', ['callback', 'event'], 'system'],
  ['radio', 'Radio', ['signal', 'live'], 'system'],
  ['rss', 'RSS', ['feed', 'subscribe'], 'system'],
  ['megaphone', 'Megaphone', ['announce', 'broadcast'], 'system'],
  ['store', 'Store', ['shop', 'market'], 'system'],
  ['shopping-bag', 'Shopping', ['buy'], 'system'],
  ['credit-card', 'Card', ['payment'], 'system'],
  ['dollar-sign', 'Dollar', ['money', 'cost'], 'system'],
  ['coins', 'Coins', ['finance'], 'system'],
  ['wallet', 'Wallet', ['payment'], 'system'],
  ['percent', 'Percent', ['discount'], 'system'],
  ['plane', 'Plane', ['travel', 'send'], 'system'],
  ['truck', 'Truck', ['delivery', 'ship'], 'system'],
  ['map', 'Map', ['location'], 'system'],
  ['map-pin', 'Map pin', ['place', 'gps'], 'system'],
  ['compass', 'Compass', ['direction', 'navigation'], 'system'],
  ['umbrella', 'Umbrella', ['weather', 'protect'], 'system'],
  ['tree-deciduous', 'Tree', ['nature', 'green'], 'system'],
  ['heart', 'Heart', ['love', 'like'], 'system'],
  ['smile', 'Smile', ['happy', 'emoji'], 'system'],
  ['thumbs-up', 'Thumbs up', ['like', 'approve'], 'system'],
  ['thumbs-down', 'Thumbs down', ['dislike'], 'system'],
  ['coffee', 'Coffee', ['drink', 'break'], 'system'],
  ['joystick', 'Joystick', ['game', 'control'], 'system'],
  ['mouse-pointer-click', 'Pointer click', ['cursor', 'click', 'browser', 'interact'], 'system'],
  // Media
  ['image', 'Image', ['picture', 'photo'], 'media'],
  ['camera', 'Camera', ['photo', 'screenshot'], 'media'],
  ['music', 'Music', ['audio', 'song'], 'media'],
  ['mic', 'Microphone', ['voice', 'record'], 'media'],
  ['play', 'Play', ['video', 'start'], 'media'],
  ['monitor', 'Monitor', ['screen', 'display'], 'media'],
  ['smartphone', 'Smartphone', ['mobile'], 'media'],
  ['tablet', 'Tablet', ['device'], 'media'],
  ['watch', 'Watch', ['wearable'], 'media'],
  ['tv', 'TV', ['television'], 'media'],
]
