// Code generated by appmanager dev_generate bundle call extraction
//
// Typed callers for bundle-level plugin permissions. Each `plugin.<dep>.<bundle>`
// permission declared in .appdef was resolved against the dependency's
// REGISTERED manifest at generation time; its bundle tools are re-exported
// here as dep-prefixed request/response structs and CallBundle* functions.
// The expansion snapshot lives in the GeneratedManifest (dev_gate drift gate).
//
// No bundle-level permissions resolved; this file is intentionally empty.

package main
