// Code generated by appmanager dev_generate host protocol extraction. DO NOT EDIT.
// Host wire types and typed callers for the callIDs declared in
// .appdef `permissions:`. Regenerate with appmanager.dev_generate.
//
// Covered host calls:
//   llm.complete -> aiaggregator.dispatch  req LLMReq  resp LLMResp  (streaming)

package main

import (
	"context"
	"encoding/json"
	"fmt"
	sdk "github.com/qomos-w/sporemind-plugin-sdk"
)

// Host schema IDs for the extracted types.
const ()

type LLMMessage struct {
	Role    string `json:"role,omitempty"`
	Content any    `json:"content,omitempty"`
}

type LLMReq struct {
	Prompt           string        `json:"prompt,omitempty"`
	Messages         []LLMMessage  `json:"messages,omitempty"`
	System           string        `json:"system,omitempty"`
	Model            string        `json:"model,omitempty"`
	Provider         string        `json:"provider,omitempty"`
	Temperature      *float64      `json:"temperature,omitempty"`
	TopP             *float64      `json:"top_p,omitempty"`
	FrequencyPenalty *float64      `json:"frequency_penalty,omitempty"`
	PresencePenalty  *float64      `json:"presence_penalty,omitempty"`
	ReasoningEffort  string        `json:"reasoning_effort,omitempty"`
	ThinkingBudget   *int32        `json:"thinking_budget,omitempty"`
	Tools            []LLMToolSpec `json:"tools,omitempty"`
	ToolChoice       string        `json:"tool_choice,omitempty"`
}

type LLMResp struct {
	Text      string          `json:"Text"`
	Reasoning string          `json:"Reasoning,omitempty"`
	Usage     json.RawMessage `json:"Usage,omitempty"`
	ToolCalls []LLMToolCall   `json:"ToolCalls,omitempty"`
}

type LLMToolCall struct {
	ID        string          `json:"Id,omitempty"`
	Name      string          `json:"Name"`
	Arguments json.RawMessage `json:"Arguments,omitempty"`
}

type LLMToolSpec struct {
	Name        string          `json:"name"`
	Description string          `json:"description,omitempty"`
	InputSchema json.RawMessage `json:"input_schema,omitempty"`
}

// CallLLMComplete invokes the host callable llm.complete (backing aiaggregator.dispatch, capability llm.invoke).
func CallLLMComplete(host sdk.Host, req LLMReq) (LLMResp, error) {
	raw, err := host.Invoke("llm.complete", req)
	if err != nil {
		return LLMResp{}, err
	}
	var resp LLMResp
	if err := json.Unmarshal(raw, &resp); err != nil {
		return LLMResp{}, fmt.Errorf("llm.complete: decode response: %w", err)
	}
	return resp, nil
}

// StreamLLMComplete streams the host callable llm.complete: chunks flow to onChunk in
// arrival order decoded as sdk.LLMChunk (via sdk.ForwardLLMChunks), the
// return value is the same aggregated terminal as the unary form.
// Transports without streaming degrade to zero chunks plus the terminal.
func StreamLLMComplete(host sdk.Host, req LLMReq, onChunk func(sdk.LLMChunk) error) (LLMResp, error) {
	return StreamLLMCompleteCtx(context.Background(), host, req, onChunk)
}

// StreamLLMCompleteCtx is StreamLLMComplete with a cancellation root: ctx expiry aborts the
// stream and (on transports implementing sdk.CanceledHost) asks the host to
// abort its upstream dispatch. Other transports keep waiting until the
// terminal arrives.
func StreamLLMCompleteCtx(ctx context.Context, host sdk.Host, req LLMReq, onChunk func(sdk.LLMChunk) error) (LLMResp, error) {
	var raw []byte
	var err error
	if ch, ok := host.(sdk.CanceledHost); ok {
		raw, err = ch.InvokeStreamCtx(ctx, "llm.complete", req, sdk.ForwardLLMChunks(onChunk))
	} else {
		raw, err = host.InvokeStream("llm.complete", req, sdk.ForwardLLMChunks(onChunk))
	}
	if err != nil {
		return LLMResp{}, err
	}
	var resp LLMResp
	if err := json.Unmarshal(raw, &resp); err != nil {
		return LLMResp{}, fmt.Errorf("llm.complete: decode terminal: %w", err)
	}
	return resp, nil
}
